# Transformer all tasks — robustness results from script

This notebook reads CSV artifacts generated by `transformer_robustness.py`.

The Transformer robustness training/evaluation itself is kept in a standalone Python script because the original notebook had kernel instability. This result notebook stays lightweight: it loads the generated CSV files and presents the same three sections as the MLP/CNN/LSTM robustness notebooks:

1. clean-train robustness results
2. augmented-train robustness results
3. clean-vs-aug score comparison

For the main fair comparison, use the manually pasted `FINAL_TUNED_CFGS` from `transformer_hyperparameter_tuning.ipynb` inside the Python script before running it.

In [1]:
from pathlib import Path
import pandas as pd

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", None)

The generating script is:

```bash
mkdir notebooks/logs/transformer_robustness
python notebooks/transformer_robustness.py --output-dir notebooks/logs/transformer_robustness
```

or, if you run it from another folder:

```bash
mkdir notebooks/logs/transformer_robustness
python transformer_robustness.py --project-root /path/to/CS7643-Project --output-dir /path/to/CS7643-Project/notebooks/logs/transformer_robustness
```

This notebook reads the saved CSV outputs and presents them in the same order as the MLP/CNN/LSTM robustness notebooks.

In [2]:
# Resolve paths assuming this notebook is run from project_root/notebooks
cwd = Path.cwd().resolve()
PROJECT_ROOT = cwd.parent if cwd.name == "notebooks" else cwd
LOG_DIR = PROJECT_ROOT / "notebooks" / "logs" / "transformer_robustness"

print("PROJECT_ROOT =", PROJECT_ROOT)
print("LOG_DIR      =", LOG_DIR)

if not LOG_DIR.exists():
    raise FileNotFoundError(f"Could not find logs directory: {LOG_DIR}")


def find_csv_by_name(log_dir: Path, filename: str) -> Path:
    matches = sorted(log_dir.rglob(filename))
    if not matches:
        raise FileNotFoundError(f"Missing required CSV: {filename} under {log_dir}")

    # Prefer a top-level file if it exists, otherwise require uniqueness.
    top_level = [p for p in matches if p.parent == log_dir]
    if len(top_level) == 1:
        return top_level[0]
    if len(matches) == 1:
        return matches[0]

    rels = "\n".join(str(p.relative_to(log_dir)) for p in matches)
    raise ValueError(
        f"Found multiple candidates for {filename}. Keep one canonical file or edit selector.\n{rels}"
    )


required_files = {
    "tuned_hparams": "tuned_hparams.csv",
    "results_clean": "results_clean.csv",
    "results_aug": "results_aug.csv",
    "cmp_delta_score": "cmp_delta_score.csv",
    "cmp_delta_score_pivot": "cmp_delta_score_pivot.csv",
    "best_metrics_summary": "best_metrics_summary.csv",
}

csv_paths = {key: find_csv_by_name(LOG_DIR, fname) for key, fname in required_files.items()}
for key, path in csv_paths.items():
    print(f"{key:>20} : {path.relative_to(LOG_DIR)}")

tuned_hparams = pd.read_csv(csv_paths["tuned_hparams"])
results_clean = pd.read_csv(csv_paths["results_clean"])
results_aug = pd.read_csv(csv_paths["results_aug"])
cmp_delta_score = pd.read_csv(csv_paths["cmp_delta_score"])
cmp_delta_score_pivot = pd.read_csv(csv_paths["cmp_delta_score_pivot"])
best_metrics_summary = pd.read_csv(csv_paths["best_metrics_summary"])

PROJECT_ROOT = /storage/ice1/7/5/kw53/cs7643/tmp/CS7643-Project
LOG_DIR      = /storage/ice1/7/5/kw53/cs7643/tmp/CS7643-Project/notebooks/logs/transformer_robustness
       tuned_hparams : tuned_hparams.csv
       results_clean : results_clean.csv
         results_aug : results_aug.csv
     cmp_delta_score : cmp_delta_score.csv
cmp_delta_score_pivot : cmp_delta_score_pivot.csv
best_metrics_summary : best_metrics_summary.csv

In [3]:
# Quick structural check: the transformer result notebook should mirror the other robustness notebooks.
print("tuned_hparams shape      :", tuned_hparams.shape)
print("results_clean shape      :", results_clean.shape)
print("results_aug shape        :", results_aug.shape)
print("cmp_delta_score shape    :", cmp_delta_score.shape)
print("pivot shape              :", cmp_delta_score_pivot.shape)
print("best_metrics_summary     :", best_metrics_summary.shape)

required_cmp_cols = {
    "scenario",
    "model",
    "score_clean_train",
    "score_aug_train",
    "delta_score",
}
missing = required_cmp_cols - set(cmp_delta_score.columns)
if missing:
    raise ValueError(f"cmp_delta_score.csv is missing columns: {missing}")

print("\nFine-tuned configs used by the script:")
display(tuned_hparams)

print("\nBest clean/aug training metrics:")
display(best_metrics_summary)

tuned_hparams shape      : (6, 18)
results_clean shape      : (108, 12)
results_aug shape        : (108, 12)
cmp_delta_score shape    : (108, 5)
pivot shape              : (18, 7)
best_metrics_summary     : (12, 14)

Fine-tuned configs used by the script:

,family,task,lr,weight_decay,max_epochs,patience,print_every,batch_size,val_batch_size,grad_clip_norm,arch_d_model,arch_nhead,arch_num_layers,arch_dim_feedforward,arch_dropout,arch_num_heads,arch_num_sab_layers,arch_num_seed_vectors
0,set,coordinate,0.0010,0.0005,50,10,5,256,512,1.0,128,NaN,NaN,256,0.1,4.0,2.0,1.0
1,standard,coordinate,0.0010,0.0001,50,10,5,256,512,1.0,128,4.0,2.0,256,0.1,NaN,NaN,NaN
2,set,joint,0.0005,0.0005,80,15,5,256,512,1.0,128,NaN,NaN,256,0.1,4.0,2.0,1.0
3,standard,joint,0.0010,0.0005,50,10,5,256,512,1.0,128,4.0,2.0,256,0.1,NaN,NaN,NaN
4,set,multitask,0.0005,0.0005,80,15,5,256,512,1.0,128,NaN,NaN,256,0.1,4.0,2.0,1.0
5,standard,multitask,0.0010,0.0001,50,10,5,256,512,1.0,128,4.0,2.0,256,0.1,NaN,NaN,NaN

Best clean/aug training metrics:

,model,train_regime,best_epoch,epoch,train_loss,val_loss,score,joint_accuracy,building_accuracy,floor_accuracy,coordinate_mean_euclidean,coordinate_rmse,coordinate_mean_euclidean_m,coordinate_rmse_m
0,transformer_joint,clean_train,48,48.0,0.011816,0.369757,0.943294,0.943294,1.0000,0.943294,NaN,NaN,NaN,NaN
1,set_transformer_joint,clean_train,41,41.0,0.019608,0.365364,0.938794,0.938794,0.9991,0.938794,NaN,NaN,NaN,NaN
2,transformer_multitask,clean_train,21,21.0,0.062508,0.240464,0.954996,0.954996,0.9991,0.954996,NaN,NaN,NaN,NaN
3,set_transformer_multitask,clean_train,28,28.0,0.086580,0.301406,0.934293,0.934293,0.9955,0.936094,NaN,NaN,NaN,NaN
4,transformer_coordinate,clean_train,40,40.0,0.010951,0.012482,-9.995122,NaN,NaN,NaN,0.113662,0.154118,9.995122,13.323050
5,set_transformer_coordinate,clean_train,50,50.0,0.009856,0.010813,-10.131620,NaN,NaN,NaN,0.113325,0.146442,10.131620,13.051028
6,transformer_joint,aug_train,11,11.0,0.103443,0.222953,0.945995,0.945995,0.9982,0.945995,NaN,NaN,NaN,NaN
7,set_transformer_joint,aug_train,12,12.0,0.126912,0.223655,0.949595,0.949595,0.9991,0.949595,NaN,NaN,NaN,NaN
8,transformer_multitask,aug_train,20,20.0,0.074884,0.189962,0.958596,0.958596,1.0000,0.958596,NaN,NaN,NaN,NaN
9,set_transformer_multitask,aug_train,15,15.0,0.133876,0.277100,0.938794,0.938794,0.9964,0.940594,NaN,NaN,NaN,NaN
10,transformer_coordinate,aug_train,19,19.0,0.011614,0.010792,-9.181859,NaN,NaN,NaN,0.104958,0.143726,9.181859,12.147345
11,set_transformer_coordinate,aug_train,7,7.0,0.016920,0.021207,-13.679850,NaN,NaN,NaN,0.155105,0.205377,13.679850,17.830126

## 1) Clean-train robustness results

This is the transformer-side equivalent of the MLP notebook cell that builds `results_clean`.

These rows answer:

- how each clean-trained transformer model performs on every degraded-condition scenario
- which exact scenario/model pairs are being compared later

In [4]:
display(results_clean)

print("Models in results_clean:")
print(sorted(results_clean["model"].unique()))

print("\nScenarios in results_clean:")
print(results_clean["scenario"].tolist() if results_clean["scenario"].nunique() <= 25 else sorted(results_clean["scenario"].unique()))

,scenario,score,joint_accuracy,building_accuracy,floor_accuracy,eval_loss,model,train_regime,coordinate_mean_euclidean,coordinate_rmse,coordinate_mean_euclidean_m,coordinate_rmse_m
0,clean,0.943294,0.943294,1.000000,0.943294,0.369757,transformer_joint,clean_train,NaN,NaN,NaN,NaN
1,dropout_0.05,0.935194,0.935194,1.000000,0.935194,0.410916,transformer_joint,clean_train,NaN,NaN,NaN,NaN
2,dropout_0.10,0.929793,0.929793,0.998200,0.929793,0.464283,transformer_joint,clean_train,NaN,NaN,NaN,NaN
3,dropout_0.15,0.924392,0.924392,0.998200,0.924392,0.511468,transformer_joint,clean_train,NaN,NaN,NaN,NaN
4,dropout_0.20,0.918092,0.918092,0.994599,0.918992,0.549671,transformer_joint,clean_train,NaN,NaN,NaN,NaN
5,dropout_0.25,0.898290,0.898290,0.992799,0.899190,0.616090,transformer_joint,clean_train,NaN,NaN,NaN,NaN
6,dropout_0.30,0.895590,0.895590,0.997300,0.895590,0.718300,transformer_joint,clean_train,NaN,NaN,NaN,NaN
7,dropout_0.35,0.867687,0.867687,0.992799,0.868587,0.912811,transformer_joint,clean_train,NaN,NaN,NaN,NaN
8,dropout_0.40,0.834383,0.834383,0.992799,0.836184,1.078135,transformer_joint,clean_train,NaN,NaN,NaN,NaN
9,dropout_0.45,0.824482,0.824482,0.981998,0.828983,1.243149,transformer_joint,clean_train,NaN,NaN,NaN,NaN
10,dropout_0.50,0.801980,0.801980,0.981098,0.806481,1.454390,transformer_joint,clean_train,NaN,NaN,NaN,NaN
11,dropout_0.60,0.735374,0.735374,0.969397,0.742574,2.102418,transformer_joint,clean_train,NaN,NaN,NaN,NaN
12,drop0.25_bias3_noise1,0.900990,0.900990,0.996400,0.900990,0.584296,transformer_joint,clean_train,NaN,NaN,NaN,NaN
13,drop0.35_bias4_noise2,0.871287,0.871287,0.994599,0.872187,0.859429,transformer_joint,clean_train,NaN,NaN,NaN,NaN
14,drop0.40_bias5_noise3,0.837084,0.837084,0.991899,0.838884,1.111380,transformer_joint,clean_train,NaN,NaN,NaN,NaN
15,drop0.15_bias6_noise0,0.931593,0.931593,0.998200,0.931593,0.454142,transformer_joint,clean_train,NaN,NaN,NaN,NaN
16,bias5_only,0.951395,0.951395,0.999100,0.951395,0.349285,transformer_joint,clean_train,NaN,NaN,NaN,NaN
17,noise3_only,0.931593,0.931593,0.999100,0.931593,0.428304,transformer_joint,clean_train,NaN,NaN,NaN,NaN
18,clean,0.938794,0.938794,0.999100,0.938794,0.365364,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
19,dropout_0.05,0.934293,0.934293,0.999100,0.934293,0.392649,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
20,dropout_0.10,0.922592,0.922592,0.998200,0.922592,0.494559,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
21,dropout_0.15,0.915392,0.915392,0.996400,0.915392,0.504989,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
22,dropout_0.20,0.909991,0.909991,0.993699,0.909991,0.543390,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
23,dropout_0.25,0.902790,0.902790,0.992799,0.902790,0.564616,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
24,dropout_0.30,0.885689,0.885689,0.996400,0.886589,0.697520,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
25,dropout_0.35,0.860486,0.860486,0.993699,0.860486,0.874819,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
26,dropout_0.40,0.861386,0.861386,0.991899,0.861386,0.917797,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
27,dropout_0.45,0.817282,0.817282,0.983798,0.820882,1.239200,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
28,dropout_0.50,0.802880,0.802880,0.978398,0.806481,1.316592,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
29,dropout_0.60,0.737174,0.737174,0.966697,0.741674,1.804734,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
30,drop0.25_bias3_noise1,0.890189,0.890189,0.994599,0.891089,0.591880,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
31,drop0.35_bias4_noise2,0.876688,0.876688,0.995500,0.876688,0.778734,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
32,drop0.40_bias5_noise3,0.829883,0.829883,0.992799,0.830783,1.060085,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
33,drop0.15_bias6_noise0,0.913591,0.913591,0.998200,0.913591,0.508978,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
34,bias5_only,0.928893,0.928893,0.997300,0.928893,0.408286,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
35,noise3_only,0.926193,0.926193,0.999100,0.926193,0.408257,set_transformer_joint,clean_train,NaN,NaN,NaN,NaN
36,clean,0.954996,0.954996,0.999100,0.954996,0.240464,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
37,dropout_0.05,0.951395,0.951395,0.998200,0.951395,0.278663,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
38,dropout_0.10,0.932493,0.932493,0.997300,0.932493,0.374405,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
39,dropout_0.15,0.920792,0.920792,0.998200,0.921692,0.388474,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
40,dropout_0.20,0.923492,0.923492,0.997300,0.923492,0.416605,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
41,dropout_0.25,0.913591,0.913591,0.997300,0.913591,0.462478,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
42,dropout_0.30,0.911791,0.911791,0.997300,0.912691,0.499329,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
43,dropout_0.35,0.867687,0.867687,0.991899,0.871287,0.766646,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
44,dropout_0.40,0.853285,0.853285,0.991899,0.855986,0.859286,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
45,dropout_0.45,0.828983,0.828983,0.990999,0.830783,1.076685,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
46,dropout_0.50,0.793879,0.793879,0.981098,0.799280,1.252412,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
47,dropout_0.60,0.741674,0.741674,0.978398,0.750675,1.660054,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
48,drop0.25_bias3_noise1,0.918092,0.918092,0.999100,0.918092,0.451421,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
49,drop0.35_bias4_noise2,0.887489,0.887489,0.994599,0.889289,0.708187,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
50,drop0.40_bias5_noise3,0.842484,0.842484,0.993699,0.847885,0.868385,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
51,drop0.15_bias6_noise0,0.935194,0.935194,0.999100,0.935194,0.348788,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
52,bias5_only,0.954095,0.954095,0.999100,0.954095,0.245124,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
53,noise3_only,0.944194,0.944194,0.999100,0.944194,0.273639,transformer_multitask,clean_train,NaN,NaN,NaN,NaN
54,clean,0.934293,0.934293,0.995500,0.936094,0.301406,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
55,dropout_0.05,0.922592,0.922592,0.995500,0.924392,0.340729,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
56,dropout_0.10,0.909091,0.909091,0.995500,0.912691,0.394271,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
57,dropout_0.15,0.898290,0.898290,0.995500,0.900090,0.449603,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
58,dropout_0.20,0.891989,0.891989,0.992799,0.893789,0.465236,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
59,dropout_0.25,0.880288,0.880288,0.993699,0.884789,0.508102,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
60,dropout_0.30,0.877588,0.877588,0.992799,0.879388,0.585866,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
61,dropout_0.35,0.828083,0.828083,0.990999,0.828983,0.800306,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
62,dropout_0.40,0.812781,0.812781,0.987399,0.816382,0.900156,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
63,dropout_0.45,0.804680,0.804680,0.986499,0.808281,1.059641,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
64,dropout_0.50,0.761476,0.761476,0.983798,0.765977,1.227428,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
65,dropout_0.60,0.708371,0.708371,0.980198,0.718272,1.655154,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
66,drop0.25_bias3_noise1,0.883888,0.883888,0.995500,0.884789,0.523886,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
67,drop0.35_bias4_noise2,0.848785,0.848785,0.992799,0.852385,0.676212,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
68,drop0.40_bias5_noise3,0.810081,0.810081,0.990099,0.813681,1.013956,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
69,drop0.15_bias6_noise0,0.914491,0.914491,0.995500,0.917192,0.397680,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
70,bias5_only,0.928893,0.928893,0.996400,0.929793,0.300485,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
71,noise3_only,0.922592,0.922592,0.996400,0.923492,0.338478,set_transformer_multitask,clean_train,NaN,NaN,NaN,NaN
72,clean,-9.995122,NaN,NaN,NaN,0.012482,transformer_coordinate,clean_train,0.113662,0.158002,9.995122,13.602349
73,dropout_0.05,-10.182077,NaN,NaN,NaN,0.012730,transformer_coordinate,clean_train,0.115790,0.159559,10.182077,13.753692
74,dropout_0.10,-10.564780,NaN,NaN,NaN,0.014140,transformer_coordinate,clean_train,0.120513,0.168164,10.564780,14.318353
75,dropout_0.15,-10.830583,NaN,NaN,NaN,0.014193,transformer_coordinate,clean_train,0.122744,0.168480,10.830583,14.451610
76,dropout_0.20,-11.251227,NaN,NaN,NaN,0.016304,transformer_coordinate,clean_train,0.127727,0.180575,11.251227,15.565486
77,dropout_0.25,-11.496462,NaN,NaN,NaN,0.015662,transformer_coordinate,clean_train,0.130153,0.176983,11.496462,15.348062
78,dropout_0.30,-11.829665,NaN,NaN,NaN,0.017387,transformer_coordinate,clean_train,0.134740,0.186477,11.829665,16.124279
79,dropout_0.35,-12.902731,NaN,NaN,NaN,0.023670,transformer_coordinate,clean_train,0.147542,0.217578,12.902731,18.726315
80,dropout_0.40,-13.887493,NaN,NaN,NaN,0.026039,transformer_coordinate,clean_train,0.159713,0.228208,13.887493,19.404289
81,dropout_0.45,-14.764481,NaN,NaN,NaN,0.028379,transformer_coordinate,clean_train,0.166715,0.238239,14.764481,20.979135
82,dropout_0.50,-15.761948,NaN,NaN,NaN,0.036249,transformer_coordinate,clean_train,0.178566,0.269256,15.761948,23.748036
83,dropout_0.60,-17.414574,NaN,NaN,NaN,0.038887,transformer_coordinate,clean_train,0.194824,0.278880,17.414574,24.993998
84,drop0.25_bias3_noise1,-11.544043,NaN,NaN,NaN,0.016136,transformer_coordinate,clean_train,0.130919,0.179647,11.544043,15.608177
85,drop0.35_bias4_noise2,-12.562180,NaN,NaN,NaN,0.019159,transformer_coordinate,clean_train,0.142930,0.195751,12.562180,16.945473
86,drop0.40_bias5_noise3,-13.600861,NaN,NaN,NaN,0.020951,transformer_coordinate,clean_train,0.152512,0.204699,13.600861,18.233019
87,drop0.15_bias6_noise0,-11.049438,NaN,NaN,NaN,0.014438,transformer_coordinate,clean_train,0.124463,0.169931,11.049438,14.794030
88,bias5_only,-10.350524,NaN,NaN,NaN,0.012754,transformer_coordinate,clean_train,0.117359,0.159714,10.350524,13.819786
89,noise3_only,-10.184922,NaN,NaN,NaN,0.013063,transformer_coordinate,clean_train,0.115492,0.161637,10.184922,13.906080
90,clean,-10.131620,NaN,NaN,NaN,0.010813,set_transformer_coordinate,clean_train,0.113325,0.147056,10.131620,13.084595
91,dropout_0.05,-10.418535,NaN,NaN,NaN,0.011392,set_transformer_coordinate,clean_train,0.116789,0.150944,10.418535,13.422478
92,dropout_0.10,-10.763223,NaN,NaN,NaN,0.012880,set_transformer_coordinate,clean_train,0.120773,0.160497,10.763223,14.189287
93,dropout_0.15,-10.952308,NaN,NaN,NaN,0.012742,set_transformer_coordinate,clean_train,0.123167,0.159636,10.952308,14.061335
94,dropout_0.20,-11.297670,NaN,NaN,NaN,0.014124,set_transformer_coordinate,clean_train,0.126687,0.168070,11.297670,14.831356
95,dropout_0.25,-11.677921,NaN,NaN,NaN,0.014502,set_transformer_coordinate,clean_train,0.130587,0.170304,11.677921,15.113198
96,dropout_0.30,-12.032147,NaN,NaN,NaN,0.016126,set_transformer_coordinate,clean_train,0.135797,0.179587,12.032147,15.897781
97,dropout_0.35,-12.738518,NaN,NaN,NaN,0.021402,set_transformer_coordinate,clean_train,0.144456,0.206891,12.738518,18.121389
98,dropout_0.40,-13.539546,NaN,NaN,NaN,0.021313,set_transformer_coordinate,clean_train,0.153438,0.206463,13.539546,17.857405
99,dropout_0.45,-14.578847,NaN,NaN,NaN,0.024367,set_transformer_coordinate,clean_train,0.162495,0.220759,14.578847,19.784550
100,dropout_0.50,-15.814152,NaN,NaN,NaN,0.035953,set_transformer_coordinate,clean_train,0.177949,0.268151,15.814152,24.036864
101,dropout_0.60,-17.340108,NaN,NaN,NaN,0.036411,set_transformer_coordinate,clean_train,0.193731,0.269857,17.340108,24.446233
102,drop0.25_bias3_noise1,-11.814255,NaN,NaN,NaN,0.014581,set_transformer_coordinate,clean_train,0.131194,0.170770,11.814255,15.343779
103,drop0.35_bias4_noise2,-12.572671,NaN,NaN,NaN,0.017034,set_transformer_coordinate,clean_train,0.140614,0.184574,12.572671,16.369120
104,drop0.40_bias5_noise3,-13.641554,NaN,NaN,NaN,0.020155,set_transformer_coordinate,clean_train,0.151341,0.200771,13.641554,18.189020
105,drop0.15_bias6_noise0,-11.069016,NaN,NaN,NaN,0.012227,set_transformer_coordinate,clean_train,0.121846,0.156376,11.069016,14.205308
106,bias5_only,-10.436355,NaN,NaN,NaN,0.011112,set_transformer_coordinate,clean_train,0.115480,0.149077,10.436355,13.379171
107,noise3_only,-10.311244,NaN,NaN,NaN,0.011240,set_transformer_coordinate,clean_train,0.115049,0.149934,10.311244,13.317630

Models in results_clean:
['set_transformer_coordinate', 'set_transformer_joint', 'set_transformer_multitask', 'transformer_coordinate', 'transformer_joint', 'transformer_multitask']

Scenarios in results_clean:
['clean', 'dropout_0.05', 'dropout_0.10', 'dropout_0.15', 'dropout_0.20', 'dropout_0.25', 'dropout_0.30', 'dropout_0.35', 'dropout_0.40', 'dropout_0.45', 'dropout_0.50', 'dropout_0.60', 'drop0.25_bias3_noise1', 'drop0.35_bias4_noise2', 'drop0.40_bias5_noise3', 'drop0.15_bias6_noise0', 'bias5_only', 'noise3_only', 'clean', 'dropout_0.05', 'dropout_0.10', 'dropout_0.15', 'dropout_0.20', 'dropout_0.25', 'dropout_0.30', 'dropout_0.35', 'dropout_0.40', 'dropout_0.45', 'dropout_0.50', 'dropout_0.60', 'drop0.25_bias3_noise1', 'drop0.35_bias4_noise2', 'drop0.40_bias5_noise3', 'drop0.15_bias6_noise0', 'bias5_only', 'noise3_only', 'clean', 'dropout_0.05', 'dropout_0.10', 'dropout_0.15', 'dropout_0.20', 'dropout_0.25', 'dropout_0.30', 'dropout_0.35', 'dropout_0.40', 'dropout_0.45', 'dropout_0.50', 'dropout_0.60', 'drop0.25_bias3_noise1', 'drop0.35_bias4_noise2', 'drop0.40_bias5_noise3', 'drop0.15_bias6_noise0', 'bias5_only', 'noise3_only', 'clean', 'dropout_0.05', 'dropout_0.10', 'dropout_0.15', 'dropout_0.20', 'dropout_0.25', 'dropout_0.30', 'dropout_0.35', 'dropout_0.40', 'dropout_0.45', 'dropout_0.50', 'dropout_0.60', 'drop0.25_bias3_noise1', 'drop0.35_bias4_noise2', 'drop0.40_bias5_noise3', 'drop0.15_bias6_noise0', 'bias5_only', 'noise3_only', 'clean', 'dropout_0.05', 'dropout_0.10', 'dropout_0.15', 'dropout_0.20', 'dropout_0.25', 'dropout_0.30', 'dropout_0.35', 'dropout_0.40', 'dropout_0.45', 'dropout_0.50', 'dropout_0.60', 'drop0.25_bias3_noise1', 'drop0.35_bias4_noise2', 'drop0.40_bias5_noise3', 'drop0.15_bias6_noise0', 'bias5_only', 'noise3_only', 'clean', 'dropout_0.05', 'dropout_0.10', 'dropout_0.15', 'dropout_0.20', 'dropout_0.25', 'dropout_0.30', 'dropout_0.35', 'dropout_0.40', 'dropout_0.45', 'dropout_0.50', 'dropout_0.60', 'drop0.25_bias3_noise1', 'drop0.35_bias4_noise2', 'drop0.40_bias5_noise3', 'drop0.15_bias6_noise0', 'bias5_only', 'noise3_only']

## 2) Augmented-train robustness results

This is the transformer-side equivalent of the MLP notebook cell that builds `results_aug`.

These rows answer:

- how each augmented-trained transformer model performs on the same robustness grid
- whether augmented training helps or hurts under each scenario

In [5]:
display(results_aug)

print("Models in results_aug:")
print(sorted(results_aug["model"].unique()))

print("\nScenario alignment check (clean vs aug):")
print(sorted(results_clean["scenario"].unique()) == sorted(results_aug["scenario"].unique()))

print("Model alignment check (clean vs aug):")
print(sorted(results_clean["model"].unique()) == sorted(results_aug["model"].unique()))

,scenario,score,joint_accuracy,building_accuracy,floor_accuracy,eval_loss,model,train_regime,coordinate_mean_euclidean,coordinate_rmse,coordinate_mean_euclidean_m,coordinate_rmse_m
0,clean,0.945995,0.945995,0.998200,0.945995,0.222953,transformer_joint,aug_train,NaN,NaN,NaN,NaN
1,dropout_0.05,0.942394,0.942394,0.998200,0.942394,0.224650,transformer_joint,aug_train,NaN,NaN,NaN,NaN
2,dropout_0.10,0.936094,0.936094,0.998200,0.936094,0.253305,transformer_joint,aug_train,NaN,NaN,NaN,NaN
3,dropout_0.15,0.927993,0.927993,0.998200,0.927993,0.274289,transformer_joint,aug_train,NaN,NaN,NaN,NaN
4,dropout_0.20,0.929793,0.929793,0.999100,0.929793,0.271903,transformer_joint,aug_train,NaN,NaN,NaN,NaN
5,dropout_0.25,0.919892,0.919892,0.997300,0.919892,0.287677,transformer_joint,aug_train,NaN,NaN,NaN,NaN
6,dropout_0.30,0.912691,0.912691,0.998200,0.912691,0.339764,transformer_joint,aug_train,NaN,NaN,NaN,NaN
7,dropout_0.35,0.891989,0.891989,0.995500,0.891989,0.421697,transformer_joint,aug_train,NaN,NaN,NaN,NaN
8,dropout_0.40,0.887489,0.887489,0.998200,0.887489,0.429453,transformer_joint,aug_train,NaN,NaN,NaN,NaN
9,dropout_0.45,0.874888,0.874888,0.997300,0.874888,0.513506,transformer_joint,aug_train,NaN,NaN,NaN,NaN
10,dropout_0.50,0.850585,0.850585,0.994599,0.851485,0.568983,transformer_joint,aug_train,NaN,NaN,NaN,NaN
11,dropout_0.60,0.785779,0.785779,0.987399,0.788479,0.774003,transformer_joint,aug_train,NaN,NaN,NaN,NaN
12,drop0.25_bias3_noise1,0.921692,0.921692,0.997300,0.922592,0.288216,transformer_joint,aug_train,NaN,NaN,NaN,NaN
13,drop0.35_bias4_noise2,0.899190,0.899190,0.996400,0.900990,0.385637,transformer_joint,aug_train,NaN,NaN,NaN,NaN
14,drop0.40_bias5_noise3,0.873987,0.873987,0.996400,0.874888,0.479223,transformer_joint,aug_train,NaN,NaN,NaN,NaN
15,drop0.15_bias6_noise0,0.926193,0.926193,0.999100,0.926193,0.290306,transformer_joint,aug_train,NaN,NaN,NaN,NaN
16,bias5_only,0.937894,0.937894,0.999100,0.937894,0.239781,transformer_joint,aug_train,NaN,NaN,NaN,NaN
17,noise3_only,0.935194,0.935194,0.998200,0.935194,0.239171,transformer_joint,aug_train,NaN,NaN,NaN,NaN
18,clean,0.949595,0.949595,0.999100,0.949595,0.223655,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
19,dropout_0.05,0.946895,0.946895,0.999100,0.946895,0.235171,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
20,dropout_0.10,0.936994,0.936994,0.998200,0.936994,0.280223,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
21,dropout_0.15,0.925293,0.925293,0.997300,0.925293,0.319322,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
22,dropout_0.20,0.926193,0.926193,0.996400,0.926193,0.320515,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
23,dropout_0.25,0.911791,0.911791,0.998200,0.911791,0.318220,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
24,dropout_0.30,0.916292,0.916292,0.995500,0.916292,0.373800,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
25,dropout_0.35,0.884789,0.884789,0.994599,0.884789,0.471462,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
26,dropout_0.40,0.876688,0.876688,0.992799,0.878488,0.503364,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
27,dropout_0.45,0.855986,0.855986,0.989199,0.858686,0.579082,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
28,dropout_0.50,0.846985,0.846985,0.990099,0.848785,0.603251,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
29,dropout_0.60,0.766877,0.766877,0.978398,0.770477,0.981321,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
30,drop0.25_bias3_noise1,0.918992,0.918992,0.994599,0.918992,0.322293,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
31,drop0.35_bias4_noise2,0.898290,0.898290,0.992799,0.898290,0.424744,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
32,drop0.40_bias5_noise3,0.872187,0.872187,0.990099,0.873087,0.522759,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
33,drop0.15_bias6_noise0,0.927093,0.927093,0.997300,0.927093,0.270745,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
34,bias5_only,0.949595,0.949595,0.999100,0.949595,0.221364,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
35,noise3_only,0.936094,0.936094,1.000000,0.936094,0.239962,set_transformer_joint,aug_train,NaN,NaN,NaN,NaN
36,clean,0.958596,0.958596,1.000000,0.958596,0.189962,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
37,dropout_0.05,0.956796,0.956796,1.000000,0.956796,0.191044,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
38,dropout_0.10,0.946895,0.946895,0.999100,0.947795,0.227553,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
39,dropout_0.15,0.936994,0.936994,0.999100,0.937894,0.257426,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
40,dropout_0.20,0.943294,0.943294,0.999100,0.944194,0.234382,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
41,dropout_0.25,0.932493,0.932493,0.999100,0.933393,0.258892,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
42,dropout_0.30,0.917192,0.917192,0.999100,0.918092,0.303759,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
43,dropout_0.35,0.895590,0.895590,0.998200,0.895590,0.446212,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
44,dropout_0.40,0.889289,0.889289,0.998200,0.891089,0.424905,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
45,dropout_0.45,0.868587,0.868587,0.997300,0.868587,0.539323,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
46,dropout_0.50,0.854185,0.854185,0.997300,0.855086,0.593120,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
47,dropout_0.60,0.786679,0.786679,0.985599,0.789379,0.897197,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
48,drop0.25_bias3_noise1,0.932493,0.932493,1.000000,0.932493,0.258964,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
49,drop0.35_bias4_noise2,0.916292,0.916292,0.997300,0.918092,0.341875,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
50,drop0.40_bias5_noise3,0.884789,0.884789,0.998200,0.885689,0.452406,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
51,drop0.15_bias6_noise0,0.946895,0.946895,1.000000,0.946895,0.222980,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
52,bias5_only,0.958596,0.958596,1.000000,0.958596,0.185405,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
53,noise3_only,0.950495,0.950495,1.000000,0.950495,0.199104,transformer_multitask,aug_train,NaN,NaN,NaN,NaN
54,clean,0.938794,0.938794,0.996400,0.940594,0.277100,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
55,dropout_0.05,0.937894,0.937894,0.996400,0.940594,0.287707,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
56,dropout_0.10,0.922592,0.922592,0.994599,0.926193,0.326859,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
57,dropout_0.15,0.918992,0.918992,0.994599,0.922592,0.348106,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
58,dropout_0.20,0.918992,0.918992,0.993699,0.923492,0.383135,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
59,dropout_0.25,0.909991,0.909991,0.994599,0.912691,0.376766,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
60,dropout_0.30,0.902790,0.902790,0.995500,0.904590,0.434407,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
61,dropout_0.35,0.863186,0.863186,0.989199,0.866787,0.556841,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
62,dropout_0.40,0.864987,0.864987,0.986499,0.869487,0.593123,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
63,dropout_0.45,0.839784,0.839784,0.987399,0.841584,0.693140,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
64,dropout_0.50,0.829883,0.829883,0.989199,0.834383,0.716012,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
65,dropout_0.60,0.765077,0.765077,0.975698,0.772277,1.056716,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
66,drop0.25_bias3_noise1,0.913591,0.913591,0.993699,0.916292,0.386699,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
67,drop0.35_bias4_noise2,0.888389,0.888389,0.992799,0.891989,0.500848,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
68,drop0.40_bias5_noise3,0.861386,0.861386,0.991899,0.864987,0.639766,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
69,drop0.15_bias6_noise0,0.918992,0.918992,0.995500,0.920792,0.337784,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
70,bias5_only,0.935194,0.935194,0.996400,0.936994,0.284022,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
71,noise3_only,0.929793,0.929793,0.997300,0.931593,0.292086,set_transformer_multitask,aug_train,NaN,NaN,NaN,NaN
72,clean,-9.181859,NaN,NaN,NaN,0.010792,transformer_coordinate,aug_train,0.104958,0.146912,9.181859,12.347404
73,dropout_0.05,-9.317622,NaN,NaN,NaN,0.011029,transformer_coordinate,aug_train,0.106568,0.148519,9.317622,12.505649
74,dropout_0.10,-9.551762,NaN,NaN,NaN,0.011915,transformer_coordinate,aug_train,0.109542,0.154370,9.551762,12.927698
75,dropout_0.15,-9.713941,NaN,NaN,NaN,0.012220,transformer_coordinate,aug_train,0.111114,0.156334,9.713941,13.145961
76,dropout_0.20,-10.087272,NaN,NaN,NaN,0.013469,transformer_coordinate,aug_train,0.115419,0.164126,10.087272,13.892656
77,dropout_0.25,-10.040259,NaN,NaN,NaN,0.012071,transformer_coordinate,aug_train,0.114436,0.155375,10.040259,13.226056
78,dropout_0.30,-10.483989,NaN,NaN,NaN,0.014207,transformer_coordinate,aug_train,0.120553,0.168563,10.483989,14.272059
79,dropout_0.35,-10.810975,NaN,NaN,NaN,0.017398,transformer_coordinate,aug_train,0.124523,0.186535,10.810975,15.833270
80,dropout_0.40,-11.179603,NaN,NaN,NaN,0.017241,transformer_coordinate,aug_train,0.128861,0.185696,11.179603,15.584838
81,dropout_0.45,-12.306575,NaN,NaN,NaN,0.021831,transformer_coordinate,aug_train,0.140319,0.208956,12.306575,18.140280
82,dropout_0.50,-13.380658,NaN,NaN,NaN,0.028301,transformer_coordinate,aug_train,0.152597,0.237912,13.380658,20.578171
83,dropout_0.60,-13.897338,NaN,NaN,NaN,0.027243,transformer_coordinate,aug_train,0.156526,0.233423,13.897338,20.635205
84,drop0.25_bias3_noise1,-10.271684,NaN,NaN,NaN,0.013722,transformer_coordinate,aug_train,0.116670,0.165661,10.271684,14.072428
85,drop0.35_bias4_noise2,-10.825883,NaN,NaN,NaN,0.014649,transformer_coordinate,aug_train,0.122579,0.171169,10.825883,14.769078
86,drop0.40_bias5_noise3,-11.656964,NaN,NaN,NaN,0.017144,transformer_coordinate,aug_train,0.131893,0.185170,11.656964,16.113320
87,drop0.15_bias6_noise0,-9.824109,NaN,NaN,NaN,0.012326,transformer_coordinate,aug_train,0.111436,0.157008,9.824109,13.258214
88,bias5_only,-9.404384,NaN,NaN,NaN,0.011118,transformer_coordinate,aug_train,0.107063,0.149114,9.404384,12.566009
89,noise3_only,-9.284266,NaN,NaN,NaN,0.010815,transformer_coordinate,aug_train,0.105635,0.147069,9.284266,12.430367
90,clean,-13.679850,NaN,NaN,NaN,0.021207,set_transformer_coordinate,aug_train,0.155105,0.205947,13.679850,17.871462
91,dropout_0.05,-13.844310,NaN,NaN,NaN,0.021750,set_transformer_coordinate,aug_train,0.156974,0.208567,13.844310,18.115281
92,dropout_0.10,-14.139616,NaN,NaN,NaN,0.023003,set_transformer_coordinate,aug_train,0.160451,0.214490,14.139616,18.556788
93,dropout_0.15,-14.419107,NaN,NaN,NaN,0.024043,set_transformer_coordinate,aug_train,0.163224,0.219285,14.419107,18.954090
94,dropout_0.20,-14.716292,NaN,NaN,NaN,0.025244,set_transformer_coordinate,aug_train,0.166682,0.224696,14.716292,19.578852
95,dropout_0.25,-14.989415,NaN,NaN,NaN,0.025972,set_transformer_coordinate,aug_train,0.169648,0.227910,14.989415,19.834124
96,dropout_0.30,-15.512732,NaN,NaN,NaN,0.028118,set_transformer_coordinate,aug_train,0.175554,0.237143,15.512732,20.789511
97,dropout_0.35,-16.108176,NaN,NaN,NaN,0.032150,set_transformer_coordinate,aug_train,0.183368,0.253575,16.108176,21.931065
98,dropout_0.40,-16.687886,NaN,NaN,NaN,0.034026,set_transformer_coordinate,aug_train,0.189779,0.260869,16.687886,22.561284
99,dropout_0.45,-17.614402,NaN,NaN,NaN,0.037086,set_transformer_coordinate,aug_train,0.198566,0.272346,17.614402,23.990831
100,dropout_0.50,-18.324112,NaN,NaN,NaN,0.041365,set_transformer_coordinate,aug_train,0.206367,0.287628,18.324112,25.512716
101,dropout_0.60,-20.310747,NaN,NaN,NaN,0.051352,set_transformer_coordinate,aug_train,0.228084,0.320474,20.310747,28.474208
102,drop0.25_bias3_noise1,-14.398059,NaN,NaN,NaN,0.023175,set_transformer_coordinate,aug_train,0.162959,0.215293,14.398059,18.779677
103,drop0.35_bias4_noise2,-14.977079,NaN,NaN,NaN,0.024765,set_transformer_coordinate,aug_train,0.168904,0.222552,14.977079,19.483303
104,drop0.40_bias5_noise3,-16.284061,NaN,NaN,NaN,0.030344,set_transformer_coordinate,aug_train,0.183296,0.246348,16.284061,21.980213
105,drop0.15_bias6_noise0,-13.618008,NaN,NaN,NaN,0.019964,set_transformer_coordinate,aug_train,0.153665,0.199819,13.618008,17.416287
106,bias5_only,-13.218786,NaN,NaN,NaN,0.018861,set_transformer_coordinate,aug_train,0.149386,0.194223,13.218786,16.920969
107,noise3_only,-13.821915,NaN,NaN,NaN,0.021738,set_transformer_coordinate,aug_train,0.156750,0.208510,13.821915,18.037280

Models in results_aug:
['set_transformer_coordinate', 'set_transformer_joint', 'set_transformer_multitask', 'transformer_coordinate', 'transformer_joint', 'transformer_multitask']

Scenario alignment check (clean vs aug):
True
Model alignment check (clean vs aug):
True

## 3) Compare `score` (clean train vs aug train)

This is the transformer-side equivalent of the MLP notebook cells that create:

- `cmp`
- the pivot table of `delta_score`

Interpretation:

- `delta_score = score_aug_train - score_clean_train`
- positive means augmented training improved the score
- negative means augmented training hurt the score

For coordinate models, confirm that the stored `score` already uses the same higher-is-better convention as the MLP notebook before drawing conclusions.

In [6]:
display(cmp_delta_score)
display(cmp_delta_score_pivot)

print("Standard Transformer rows:")
display(cmp_delta_score[cmp_delta_score["model"].str.startswith("transformer_")])

print("Set Transformer rows:")
display(cmp_delta_score[cmp_delta_score["model"].str.startswith("set_transformer_")])

                  scenario                       model  score_clean_train  score_aug_train  delta_score
0                    clean  set_transformer_coordinate         -10.131620       -13.679850    -3.548230
1             dropout_0.05  set_transformer_coordinate         -10.418535       -13.844310    -3.425776
2             dropout_0.10  set_transformer_coordinate         -10.763223       -14.139616    -3.376393
3             dropout_0.15  set_transformer_coordinate         -10.952308       -14.419107    -3.466799
4             dropout_0.20  set_transformer_coordinate         -11.297670       -14.716292    -3.418622
5             dropout_0.25  set_transformer_coordinate         -11.677921       -14.989415    -3.311494
6             dropout_0.30  set_transformer_coordinate         -12.032147       -15.512732    -3.480585
7             dropout_0.35  set_transformer_coordinate         -12.738518       -16.108176    -3.369658
8             dropout_0.40  set_transformer_coordinate         -13.539546       -16.687886    -3.148340
9             dropout_0.45  set_transformer_coordinate         -14.578847       -17.614402    -3.035555
10            dropout_0.50  set_transformer_coordinate         -15.814152       -18.324112    -2.509960
11            dropout_0.60  set_transformer_coordinate         -17.340108       -20.310747    -2.970640
12   drop0.25_bias3_noise1  set_transformer_coordinate         -11.814255       -14.398059    -2.583805
13   drop0.35_bias4_noise2  set_transformer_coordinate         -12.572671       -14.977079    -2.404408
14   drop0.40_bias5_noise3  set_transformer_coordinate         -13.641554       -16.284061    -2.642507
15   drop0.15_bias6_noise0  set_transformer_coordinate         -11.069016       -13.618008    -2.548992
16              bias5_only  set_transformer_coordinate         -10.436355       -13.218786    -2.782431
17             noise3_only  set_transformer_coordinate         -10.311244       -13.821915    -3.510671
18                   clean       set_transformer_joint           0.938794         0.949595     0.010801
19            dropout_0.05       set_transformer_joint           0.934293         0.946895     0.012601
20            dropout_0.10       set_transformer_joint           0.922592         0.936994     0.014401
21            dropout_0.15       set_transformer_joint           0.915392         0.925293     0.009901
22            dropout_0.20       set_transformer_joint           0.909991         0.926193     0.016202
23            dropout_0.25       set_transformer_joint           0.902790         0.911791     0.009001
24            dropout_0.30       set_transformer_joint           0.885689         0.916292     0.030603
25            dropout_0.35       set_transformer_joint           0.860486         0.884789     0.024302
26            dropout_0.40       set_transformer_joint           0.861386         0.876688     0.015302
27            dropout_0.45       set_transformer_joint           0.817282         0.855986     0.038704
28            dropout_0.50       set_transformer_joint           0.802880         0.846985     0.044104
29            dropout_0.60       set_transformer_joint           0.737174         0.766877     0.029703
30   drop0.25_bias3_noise1       set_transformer_joint           0.890189         0.918992     0.028803
31   drop0.35_bias4_noise2       set_transformer_joint           0.876688         0.898290     0.021602
32   drop0.40_bias5_noise3       set_transformer_joint           0.829883         0.872187     0.042304
33   drop0.15_bias6_noise0       set_transformer_joint           0.913591         0.927093     0.013501
34              bias5_only       set_transformer_joint           0.928893         0.949595     0.020702
35             noise3_only       set_transformer_joint           0.926193         0.936094     0.009901
36                   clean   set_transformer_multitask           0.934293         0.938794     0.004500
37            dropout_0.05   set_transformer_multitask           0.922592         0.937894     0.015302
38            dropout_0.10   set_transformer_multitask           0.909091         0.922592     0.013501
39            dropout_0.15   set_transformer_multitask           0.898290         0.918992     0.020702
40            dropout_0.20   set_transformer_multitask           0.891989         0.918992     0.027003
41            dropout_0.25   set_transformer_multitask           0.880288         0.909991     0.029703
42            dropout_0.30   set_transformer_multitask           0.877588         0.902790     0.025203
43            dropout_0.35   set_transformer_multitask           0.828083         0.863186     0.035104
44            dropout_0.40   set_transformer_multitask           0.812781         0.864987     0.052205
45            dropout_0.45   set_transformer_multitask           0.804680         0.839784     0.035104
46            dropout_0.50   set_transformer_multitask           0.761476         0.829883     0.068407
47            dropout_0.60   set_transformer_multitask           0.708371         0.765077     0.056706
48   drop0.25_bias3_noise1   set_transformer_multitask           0.883888         0.913591     0.029703
49   drop0.35_bias4_noise2   set_transformer_multitask           0.848785         0.888389     0.039604
50   drop0.40_bias5_noise3   set_transformer_multitask           0.810081         0.861386     0.051305
51   drop0.15_bias6_noise0   set_transformer_multitask           0.914491         0.918992     0.004500
52              bias5_only   set_transformer_multitask           0.928893         0.935194     0.006301
53             noise3_only   set_transformer_multitask           0.922592         0.929793     0.007201
54                   clean      transformer_coordinate          -9.995122        -9.181859     0.813263
55            dropout_0.05      transformer_coordinate         -10.182077        -9.317622     0.864455
56            dropout_0.10      transformer_coordinate         -10.564780        -9.551762     1.013018
57            dropout_0.15      transformer_coordinate         -10.830583        -9.713941     1.116641
58            dropout_0.20      transformer_coordinate         -11.251227       -10.087272     1.163955
59            dropout_0.25      transformer_coordinate         -11.496462       -10.040259     1.456203
60            dropout_0.30      transformer_coordinate         -11.829665       -10.483989     1.345676
61            dropout_0.35      transformer_coordinate         -12.902731       -10.810975     2.091756
62            dropout_0.40      transformer_coordinate         -13.887493       -11.179603     2.707890
63            dropout_0.45      transformer_coordinate         -14.764481       -12.306575     2.457906
64            dropout_0.50      transformer_coordinate         -15.761948       -13.380658     2.381290
65            dropout_0.60      transformer_coordinate         -17.414574       -13.897338     3.517237
66   drop0.25_bias3_noise1      transformer_coordinate         -11.544043       -10.271684     1.272359
67   drop0.35_bias4_noise2      transformer_coordinate         -12.562180       -10.825883     1.736297
68   drop0.40_bias5_noise3      transformer_coordinate         -13.600861       -11.656964     1.943897
69   drop0.15_bias6_noise0      transformer_coordinate         -11.049438        -9.824109     1.225329
70              bias5_only      transformer_coordinate         -10.350524        -9.404384     0.946140
71             noise3_only      transformer_coordinate         -10.184922        -9.284266     0.900656
72                   clean           transformer_joint           0.943294         0.945995     0.002700
73            dropout_0.05           transformer_joint           0.935194         0.942394     0.007201
74            dropout_0.10           transformer_joint           0.929793         0.936094     0.006301
75            dropout_0.15           transformer_joint           0.924392         0.927993     0.003600
76            dropout_0.20           transformer_joint           0.918092         0.929793     0.011701
77            dropout_0.25           transformer_joint           0.898290         0.919892     0.021602
78            dropout_0.30           transformer_joint           0.895590         0.912691     0.017102
79            dropout_0.35           transformer_joint           0.867687         0.891989     0.024302
80            dropout_0.40           transformer_joint           0.834383         0.887489     0.053105
81            dropout_0.45           transformer_joint           0.824482         0.874888     0.050405
82            dropout_0.50           transformer_joint           0.801980         0.850585     0.048605
83            dropout_0.60           transformer_joint           0.735374         0.785779     0.050405
84   drop0.25_bias3_noise1           transformer_joint           0.900990         0.921692     0.020702
85   drop0.35_bias4_noise2           transformer_joint           0.871287         0.899190     0.027903
86   drop0.40_bias5_noise3           transformer_joint           0.837084         0.873987     0.036904
87   drop0.15_bias6_noise0           transformer_joint           0.931593         0.926193    -0.005401
88              bias5_only           transformer_joint           0.951395         0.937894    -0.013501
89             noise3_only           transformer_joint           0.931593         0.935194     0.003600
90                   clean       transformer_multitask           0.954996         0.958596     0.003600
91            dropout_0.05       transformer_multitask           0.951395         0.956796     0.005401
92            dropout_0.10       transformer_multitask           0.932493         0.946895     0.014401
93            dropout_0.15       transformer_multitask           0.920792         0.936994     0.016202
94            dropout_0.20       transformer_multitask           0.923492         0.943294     0.019802
95            dropout_0.25       transformer_multitask           0.913591         0.932493     0.018902
96            dropout_0.30       transformer_multitask           0.911791         0.917192     0.005401
97            dropout_0.35       transformer_multitask           0.867687         0.895590     0.027903
98            dropout_0.40       transformer_multitask           0.853285         0.889289     0.036004
99            dropout_0.45       transformer_multitask           0.828983         0.868587     0.039604
100           dropout_0.50       transformer_multitask           0.793879         0.854185     0.060306
101           dropout_0.60       transformer_multitask           0.741674         0.786679     0.045004
102  drop0.25_bias3_noise1       transformer_multitask           0.918092         0.932493     0.014401
103  drop0.35_bias4_noise2       transformer_multitask           0.887489         0.916292     0.028803
104  drop0.40_bias5_noise3       transformer_multitask           0.842484         0.884789     0.042304
105  drop0.15_bias6_noise0       transformer_multitask           0.935194         0.946895     0.011701
106             bias5_only       transformer_multitask           0.954095         0.958596     0.004500
107            noise3_only       transformer_multitask           0.944194         0.950495     0.006301

                 scenario  set_transformer_coordinate  set_transformer_joint  set_transformer_multitask  transformer_coordinate  transformer_joint  transformer_multitask
0                   clean                   -3.548230               0.010801                   0.004500                0.813263           0.002700               0.003600
1            dropout_0.05                   -3.425776               0.012601                   0.015302                0.864455           0.007201               0.005401
2            dropout_0.10                   -3.376393               0.014401                   0.013501                1.013018           0.006301               0.014401
3            dropout_0.15                   -3.466799               0.009901                   0.020702                1.116641           0.003600               0.016202
4            dropout_0.20                   -3.418622               0.016202                   0.027003                1.163955           0.011701               0.019802
5            dropout_0.25                   -3.311494               0.009001                   0.029703                1.456203           0.021602               0.018902
6            dropout_0.30                   -3.480585               0.030603                   0.025203                1.345676           0.017102               0.005401
7            dropout_0.35                   -3.369658               0.024302                   0.035104                2.091756           0.024302               0.027903
8            dropout_0.40                   -3.148340               0.015302                   0.052205                2.707890           0.053105               0.036004
9            dropout_0.45                   -3.035555               0.038704                   0.035104                2.457906           0.050405               0.039604
10           dropout_0.50                   -2.509960               0.044104                   0.068407                2.381290           0.048605               0.060306
11           dropout_0.60                   -2.970640               0.029703                   0.056706                3.517237           0.050405               0.045004
12  drop0.25_bias3_noise1                   -2.583805               0.028803                   0.029703                1.272359           0.020702               0.014401
13  drop0.35_bias4_noise2                   -2.404408               0.021602                   0.039604                1.736297           0.027903               0.028803
14  drop0.40_bias5_noise3                   -2.642507               0.042304                   0.051305                1.943897           0.036904               0.042304
15  drop0.15_bias6_noise0                   -2.548992               0.013501                   0.004500                1.225329          -0.005401               0.011701
16             bias5_only                   -2.782431               0.020702                   0.006301                0.946140          -0.013501               0.004500
17            noise3_only                   -3.510671               0.009901                   0.007201                0.900656           0.003600               0.006301

Standard Transformer rows:

                  scenario                   model  score_clean_train  score_aug_train  delta_score
54                   clean  transformer_coordinate          -9.995122        -9.181859     0.813263
55            dropout_0.05  transformer_coordinate         -10.182077        -9.317622     0.864455
56            dropout_0.10  transformer_coordinate         -10.564780        -9.551762     1.013018
57            dropout_0.15  transformer_coordinate         -10.830583        -9.713941     1.116641
58            dropout_0.20  transformer_coordinate         -11.251227       -10.087272     1.163955
59            dropout_0.25  transformer_coordinate         -11.496462       -10.040259     1.456203
60            dropout_0.30  transformer_coordinate         -11.829665       -10.483989     1.345676
61            dropout_0.35  transformer_coordinate         -12.902731       -10.810975     2.091756
62            dropout_0.40  transformer_coordinate         -13.887493       -11.179603     2.707890
63            dropout_0.45  transformer_coordinate         -14.764481       -12.306575     2.457906
64            dropout_0.50  transformer_coordinate         -15.761948       -13.380658     2.381290
65            dropout_0.60  transformer_coordinate         -17.414574       -13.897338     3.517237
66   drop0.25_bias3_noise1  transformer_coordinate         -11.544043       -10.271684     1.272359
67   drop0.35_bias4_noise2  transformer_coordinate         -12.562180       -10.825883     1.736297
68   drop0.40_bias5_noise3  transformer_coordinate         -13.600861       -11.656964     1.943897
69   drop0.15_bias6_noise0  transformer_coordinate         -11.049438        -9.824109     1.225329
70              bias5_only  transformer_coordinate         -10.350524        -9.404384     0.946140
71             noise3_only  transformer_coordinate         -10.184922        -9.284266     0.900656
72                   clean       transformer_joint           0.943294         0.945995     0.002700
73            dropout_0.05       transformer_joint           0.935194         0.942394     0.007201
74            dropout_0.10       transformer_joint           0.929793         0.936094     0.006301
75            dropout_0.15       transformer_joint           0.924392         0.927993     0.003600
76            dropout_0.20       transformer_joint           0.918092         0.929793     0.011701
77            dropout_0.25       transformer_joint           0.898290         0.919892     0.021602
78            dropout_0.30       transformer_joint           0.895590         0.912691     0.017102
79            dropout_0.35       transformer_joint           0.867687         0.891989     0.024302
80            dropout_0.40       transformer_joint           0.834383         0.887489     0.053105
81            dropout_0.45       transformer_joint           0.824482         0.874888     0.050405
82            dropout_0.50       transformer_joint           0.801980         0.850585     0.048605
83            dropout_0.60       transformer_joint           0.735374         0.785779     0.050405
84   drop0.25_bias3_noise1       transformer_joint           0.900990         0.921692     0.020702
85   drop0.35_bias4_noise2       transformer_joint           0.871287         0.899190     0.027903
86   drop0.40_bias5_noise3       transformer_joint           0.837084         0.873987     0.036904
87   drop0.15_bias6_noise0       transformer_joint           0.931593         0.926193    -0.005401
88              bias5_only       transformer_joint           0.951395         0.937894    -0.013501
89             noise3_only       transformer_joint           0.931593         0.935194     0.003600
90                   clean   transformer_multitask           0.954996         0.958596     0.003600
91            dropout_0.05   transformer_multitask           0.951395         0.956796     0.005401
92            dropout_0.10   transformer_multitask           0.932493         0.946895     0.014401
93            dropout_0.15   transformer_multitask           0.920792         0.936994     0.016202
94            dropout_0.20   transformer_multitask           0.923492         0.943294     0.019802
95            dropout_0.25   transformer_multitask           0.913591         0.932493     0.018902
96            dropout_0.30   transformer_multitask           0.911791         0.917192     0.005401
97            dropout_0.35   transformer_multitask           0.867687         0.895590     0.027903
98            dropout_0.40   transformer_multitask           0.853285         0.889289     0.036004
99            dropout_0.45   transformer_multitask           0.828983         0.868587     0.039604
100           dropout_0.50   transformer_multitask           0.793879         0.854185     0.060306
101           dropout_0.60   transformer_multitask           0.741674         0.786679     0.045004
102  drop0.25_bias3_noise1   transformer_multitask           0.918092         0.932493     0.014401
103  drop0.35_bias4_noise2   transformer_multitask           0.887489         0.916292     0.028803
104  drop0.40_bias5_noise3   transformer_multitask           0.842484         0.884789     0.042304
105  drop0.15_bias6_noise0   transformer_multitask           0.935194         0.946895     0.011701
106             bias5_only   transformer_multitask           0.954095         0.958596     0.004500
107            noise3_only   transformer_multitask           0.944194         0.950495     0.006301

Set Transformer rows:

                 scenario                       model  score_clean_train  score_aug_train  delta_score
0                   clean  set_transformer_coordinate         -10.131620       -13.679850    -3.548230
1            dropout_0.05  set_transformer_coordinate         -10.418535       -13.844310    -3.425776
2            dropout_0.10  set_transformer_coordinate         -10.763223       -14.139616    -3.376393
3            dropout_0.15  set_transformer_coordinate         -10.952308       -14.419107    -3.466799
4            dropout_0.20  set_transformer_coordinate         -11.297670       -14.716292    -3.418622
5            dropout_0.25  set_transformer_coordinate         -11.677921       -14.989415    -3.311494
6            dropout_0.30  set_transformer_coordinate         -12.032147       -15.512732    -3.480585
7            dropout_0.35  set_transformer_coordinate         -12.738518       -16.108176    -3.369658
8            dropout_0.40  set_transformer_coordinate         -13.539546       -16.687886    -3.148340
9            dropout_0.45  set_transformer_coordinate         -14.578847       -17.614402    -3.035555
10           dropout_0.50  set_transformer_coordinate         -15.814152       -18.324112    -2.509960
11           dropout_0.60  set_transformer_coordinate         -17.340108       -20.310747    -2.970640
12  drop0.25_bias3_noise1  set_transformer_coordinate         -11.814255       -14.398059    -2.583805
13  drop0.35_bias4_noise2  set_transformer_coordinate         -12.572671       -14.977079    -2.404408
14  drop0.40_bias5_noise3  set_transformer_coordinate         -13.641554       -16.284061    -2.642507
15  drop0.15_bias6_noise0  set_transformer_coordinate         -11.069016       -13.618008    -2.548992
16             bias5_only  set_transformer_coordinate         -10.436355       -13.218786    -2.782431
17            noise3_only  set_transformer_coordinate         -10.311244       -13.821915    -3.510671
18                  clean       set_transformer_joint           0.938794         0.949595     0.010801
19           dropout_0.05       set_transformer_joint           0.934293         0.946895     0.012601
20           dropout_0.10       set_transformer_joint           0.922592         0.936994     0.014401
21           dropout_0.15       set_transformer_joint           0.915392         0.925293     0.009901
22           dropout_0.20       set_transformer_joint           0.909991         0.926193     0.016202
23           dropout_0.25       set_transformer_joint           0.902790         0.911791     0.009001
24           dropout_0.30       set_transformer_joint           0.885689         0.916292     0.030603
25           dropout_0.35       set_transformer_joint           0.860486         0.884789     0.024302
26           dropout_0.40       set_transformer_joint           0.861386         0.876688     0.015302
27           dropout_0.45       set_transformer_joint           0.817282         0.855986     0.038704
28           dropout_0.50       set_transformer_joint           0.802880         0.846985     0.044104
29           dropout_0.60       set_transformer_joint           0.737174         0.766877     0.029703
30  drop0.25_bias3_noise1       set_transformer_joint           0.890189         0.918992     0.028803
31  drop0.35_bias4_noise2       set_transformer_joint           0.876688         0.898290     0.021602
32  drop0.40_bias5_noise3       set_transformer_joint           0.829883         0.872187     0.042304
33  drop0.15_bias6_noise0       set_transformer_joint           0.913591         0.927093     0.013501
34             bias5_only       set_transformer_joint           0.928893         0.949595     0.020702
35            noise3_only       set_transformer_joint           0.926193         0.936094     0.009901
36                  clean   set_transformer_multitask           0.934293         0.938794     0.004500
37           dropout_0.05   set_transformer_multitask           0.922592         0.937894     0.015302
38           dropout_0.10   set_transformer_multitask           0.909091         0.922592     0.013501
39           dropout_0.15   set_transformer_multitask           0.898290         0.918992     0.020702
40           dropout_0.20   set_transformer_multitask           0.891989         0.918992     0.027003
41           dropout_0.25   set_transformer_multitask           0.880288         0.909991     0.029703
42           dropout_0.30   set_transformer_multitask           0.877588         0.902790     0.025203
43           dropout_0.35   set_transformer_multitask           0.828083         0.863186     0.035104
44           dropout_0.40   set_transformer_multitask           0.812781         0.864987     0.052205
45           dropout_0.45   set_transformer_multitask           0.804680         0.839784     0.035104
46           dropout_0.50   set_transformer_multitask           0.761476         0.829883     0.068407
47           dropout_0.60   set_transformer_multitask           0.708371         0.765077     0.056706
48  drop0.25_bias3_noise1   set_transformer_multitask           0.883888         0.913591     0.029703
49  drop0.35_bias4_noise2   set_transformer_multitask           0.848785         0.888389     0.039604
50  drop0.40_bias5_noise3   set_transformer_multitask           0.810081         0.861386     0.051305
51  drop0.15_bias6_noise0   set_transformer_multitask           0.914491         0.918992     0.004500
52             bias5_only   set_transformer_multitask           0.928893         0.935194     0.006301
53            noise3_only   set_transformer_multitask           0.922592         0.929793     0.007201

## Appendix — inventory of available CSV files

These cells are optional. They help when the log directory contains extra files or multiple seed-run folders.

In [7]:
csv_paths_all = sorted(LOG_DIR.rglob("*.csv"))
inventory_rows = []
for p in csv_paths_all:
    rel = p.relative_to(LOG_DIR)
    inventory_rows.append({
        "relative_path": str(rel),
        "parent": str(rel.parent),
        "filename": p.name,
        "size_bytes": p.stat().st_size,
    })

inventory_df = pd.DataFrame(inventory_rows).sort_values(["filename", "relative_path"]).reset_index(drop=True)
display(inventory_df)

               relative_path parent                   filename  size_bytes
0   best_metrics_summary.csv      .   best_metrics_summary.csv        2179
1        cmp_delta_score.csv      .        cmp_delta_score.csv       10411
2  cmp_delta_score_pivot.csv      .  cmp_delta_score_pivot.csv        2590
3            results_aug.csv      .            results_aug.csv       16606
4          results_clean.csv      .          results_clean.csv       16916
5          tuned_hparams.csv      .          tuned_hparams.csv         672