# Transformer Hyperparameter Tuning

This notebook runs a hyperparameter tuning with the fairness rule below. 

Main fairness rule:
- fixed compact Transformer architectures
- same small grid style as CNN/LSTM/MLP
- model selection on clean validation score only
- 3-seed confirmation after choosing the best candidate

This makes the Transformer comparison safer. The goal is not to find the absolute best Transformer; the goal is to compare a reasonable Transformer under the same experimental discipline as the other families.

Import policy: this notebook imports the original project modules under `src/models/` and does not depend on any alternate file suffixes or renamed class aliases.

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().resolve()
while not (PROJECT_ROOT / "src").exists():
    if PROJECT_ROOT.parent == PROJECT_ROOT:
        raise RuntimeError("Could not find project root containing 'src'. Run this notebook from inside the project repo.")
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) in sys.path:
    sys.path.remove(str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT))

print("PROJECT_ROOT =", PROJECT_ROOT)

PROJECT_ROOT = /storage/ice1/7/5/kw53/cs7643/tmp/CS7643-Project

In [2]:
import random
import numpy as np
import torch

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

    # Keep deterministic behavior when possible.
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [3]:
import pandas as pd
import torch

from src.data_prep import prepare_uji_data
from src.training import TrainConfig, train_from_tensors

from src.models.standard_transformer import (
    TransformerConfig,
    JointTransformerModel,
    MultiTaskTransformerModel,
    CoordinateTransformerModel,
)
from src.models.set_transformer import (
    SetTransformerConfig,
    JointSetTransformerModel,
    MultiTaskSetTransformerModel,
    CoordinateSetTransformerModel,
)

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 200)

In [4]:
bundle = prepare_uji_data()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

joint_y_train, joint_y_val = bundle.get_targets(["joint"])
mt_y_train, mt_y_val = bundle.get_targets(["building", "floor"])
coord_y_train, coord_y_val = bundle.get_targets(["longitude", "latitude"])

in_dim = bundle.X_train.shape[1]

print("device:", device)
print("X train/val:", bundle.X_train.shape, bundle.X_val.shape)
print("coordinate_std:", bundle.coordinate_std)

device: cuda
X train/val: (19937, 1040) (1111, 1040)
coordinate_std: [123.39891  66.94215]

## Fixed architecture choices

In [5]:
# Fixed architecture choices for main fair comparison.
# These are intentionally compact and are not selected by Optuna architecture search.
STANDARD_ARCH = dict(
    d_model=128,
    nhead=4,
    num_layers=2,
    dim_feedforward=256,
)

SET_ARCH = dict(
    d_model=128,
    num_heads=4,
    num_sab_layers=2,
    dim_feedforward=256,
    num_seed_vectors=1,
)

STANDARD_ARCH, SET_ARCH

({'d_model': 128, 'nhead': 4, 'num_layers': 2, 'dim_feedforward': 256},
 {'d_model': 128,
  'num_heads': 4,
  'num_sab_layers': 2,
  'dim_feedforward': 256,
  'num_seed_vectors': 1})

## Shared helpers

In [6]:
def count_trainable_params(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

def make_cfg(
    *,
    lr=2e-3,
    weight_decay=1e-4,
    batch_size=256,
    val_batch_size=512,
    max_epochs=30,
    patience=5,
    print_every=5,
    grad_clip_norm=None,
    run_name=None,
):
    return TrainConfig(
        lr=lr,
        weight_decay=weight_decay,
        batch_size=batch_size,
        val_batch_size=val_batch_size,
        max_epochs=max_epochs,
        patience=patience,
        print_every=print_every,
        grad_clip_norm=grad_clip_norm,
        run_name=run_name,
    )

def result_row(name, result):
    row = {"model": name, "best_epoch": result.best_epoch}
    row.update(result.best_metrics)
    return row

def run_trial(model, y_train, y_val, cfg, *, family, task, seed=42):
    set_seed(seed)
    result = train_from_tensors(
        model=model,
        X_train=bundle.X_train,
        y_train=y_train,
        X_val=bundle.X_val,
        y_val=y_val,
        device=device,
        cfg=cfg,
    )
    row = {
        "family": family,
        "task": task,
        "run_name": cfg.run_name,
        "seed": seed,
        "lr": cfg.lr,
        "weight_decay": cfg.weight_decay,
        "batch_size": cfg.batch_size,
        "val_batch_size": cfg.val_batch_size,
        "max_epochs": cfg.max_epochs,
        "patience": cfg.patience,
        "print_every": cfg.print_every,
        "grad_clip_norm": cfg.grad_clip_norm,
        "best_epoch": result.best_epoch,
    }
    row.update(result.best_metrics)
    return row

def task_data(task_name):
    if task_name == "joint":
        return joint_y_train, joint_y_val
    if task_name == "multitask":
        return mt_y_train, mt_y_val
    if task_name == "coordinate":
        return coord_y_train, coord_y_val
    raise ValueError(task_name)

def build_model(family, task_name, *, dropout=0.10):
    if family == "standard":
        backbone_cfg = TransformerConfig(
            d_model=STANDARD_ARCH["d_model"],
            nhead=STANDARD_ARCH["nhead"],
            num_layers=STANDARD_ARCH["num_layers"],
            dim_feedforward=STANDARD_ARCH["dim_feedforward"],
            dropout=dropout,
        )
        if task_name == "joint":
            return JointTransformerModel(in_dim=in_dim, backbone_cfg=backbone_cfg)
        if task_name == "multitask":
            return MultiTaskTransformerModel(in_dim=in_dim, backbone_cfg=backbone_cfg)
        if task_name == "coordinate":
            return CoordinateTransformerModel(
                in_dim=in_dim,
                coordinate_std=bundle.coordinate_std,
                backbone_cfg=backbone_cfg,
            )

    if family == "set":
        backbone_cfg = SetTransformerConfig(
            d_model=SET_ARCH["d_model"],
            num_heads=SET_ARCH["num_heads"],
            num_sab_layers=SET_ARCH["num_sab_layers"],
            dim_feedforward=SET_ARCH["dim_feedforward"],
            dropout=dropout,
            num_seed_vectors=SET_ARCH["num_seed_vectors"],
        )
        if task_name == "joint":
            return JointSetTransformerModel(in_dim=in_dim, backbone_cfg=backbone_cfg)
        if task_name == "multitask":
            return MultiTaskSetTransformerModel(in_dim=in_dim, backbone_cfg=backbone_cfg)
        if task_name == "coordinate":
            return CoordinateSetTransformerModel(
                in_dim=in_dim,
                coordinate_std=bundle.coordinate_std,
                backbone_cfg=backbone_cfg,
            )

    raise ValueError((family, task_name))

## Parameter-count sanity check

In [7]:
param_rows = []

for family in ["standard", "set"]:
    for task_name in ["joint", "multitask", "coordinate"]:
        model = build_model(family, task_name, dropout=0.10)
        param_rows.append({
            "family": family,
            "task": task_name,
            "model": f"{family}_transformer_{task_name}",
            "params": count_trainable_params(model),
        })

param_df = pd.DataFrame(param_rows)
param_df["params_millions"] = param_df["params"] / 1_000_000
param_df

     family        task                            model  params  params_millions
0  standard       joint       standard_transformer_joint  350861         0.350861
1  standard   multitask   standard_transformer_multitask  366728         0.366728
2  standard  coordinate  standard_transformer_coordinate  349442         0.349442
3       set       joint            set_transformer_joint  483213         0.483213
4       set   multitask        set_transformer_multitask  499080         0.499080
5       set  coordinate       set_transformer_coordinate  481794         0.481794

## Tuning grids

This is the final bounded Transformer tuning protocol for the main fair comparison.

Rules:
- fixed compact Standard Transformer architecture
- fixed compact Set Transformer architecture
- no Optuna
- no width/depth/head/seed-vector architecture search
- dropout fixed at 0.10
- five optimizer/schedule candidates per task and family
- selection on clean validation score only
- 3-seed confirmation after selection

This keeps Transformer tuning close to the CNN/LSTM/MLP tuning discipline.

In [8]:
BASELINE_CFG = dict(
    lr=2e-3,
    weight_decay=1e-4,
    batch_size=256,
    val_batch_size=512,
    max_epochs=30,
    patience=5,
    print_every=5,
    grad_clip_norm=1.0,
    dropout=0.10,
)

# Bounded 5-candidate grid.
# Architecture is fixed; dropout is fixed at 0.10.
# We only vary optimizer/schedule settings, matching the CNN/MLP tuning discipline.
def transformer_specs(prefix: str):
    return [
        dict(run_name=f"{prefix}_base_2e3_wd1e4",        lr=2e-3, weight_decay=1e-4, max_epochs=30, patience=5,  grad_clip_norm=1.0, dropout=0.10),
        dict(run_name=f"{prefix}_stable_1e3_wd1e4",     lr=1e-3, weight_decay=1e-4, max_epochs=50, patience=10, grad_clip_norm=1.0, dropout=0.10),
        dict(run_name=f"{prefix}_reg_1e3_wd5e4",        lr=1e-3, weight_decay=5e-4, max_epochs=50, patience=10, grad_clip_norm=1.0, dropout=0.10),
        dict(run_name=f"{prefix}_low_5e4_wd1e4",        lr=5e-4, weight_decay=1e-4, max_epochs=60, patience=12, grad_clip_norm=1.0, dropout=0.10),
        dict(run_name=f"{prefix}_lowreg_5e4_wd5e4",     lr=5e-4, weight_decay=5e-4, max_epochs=80, patience=15, grad_clip_norm=1.0, dropout=0.10),
    ]

TRANSFORMER_GRIDS = {
    "joint": [
        {**spec, "run_name": spec["run_name"].replace("xf", "{family}_joint")}
        for spec in transformer_specs("xf")
    ],
    "multitask": [
        {**spec, "run_name": spec["run_name"].replace("xf", "{family}_mt")}
        for spec in transformer_specs("xf")
    ],
    "coordinate": [
        {**spec, "run_name": spec["run_name"].replace("xf", "{family}_coord")}
        for spec in transformer_specs("xf")
    ],
}

BASELINE_CFG, TRANSFORMER_GRIDS

({'lr': 0.002,
  'weight_decay': 0.0001,
  'batch_size': 256,
  'val_batch_size': 512,
  'max_epochs': 30,
  'patience': 5,
  'print_every': 5,
  'grad_clip_norm': 1.0,
  'dropout': 0.1},
 {'joint': [{'run_name': '{family}_joint_base_2e3_wd1e4',
    'lr': 0.002,
    'weight_decay': 0.0001,
    'max_epochs': 30,
    'patience': 5,
    'grad_clip_norm': 1.0,
    'dropout': 0.1},
   {'run_name': '{family}_joint_stable_1e3_wd1e4',
    'lr': 0.001,
    'weight_decay': 0.0001,
    'max_epochs': 50,
    'patience': 10,
    'grad_clip_norm': 1.0,
    'dropout': 0.1},
   {'run_name': '{family}_joint_reg_1e3_wd5e4',
    'lr': 0.001,
    'weight_decay': 0.0005,
    'max_epochs': 50,
    'patience': 10,
    'grad_clip_norm': 1.0,
    'dropout': 0.1},
   {'run_name': '{family}_joint_low_5e4_wd1e4',
    'lr': 0.0005,
    'weight_decay': 0.0001,
    'max_epochs': 60,
    'patience': 12,
    'grad_clip_norm': 1.0,
    'dropout': 0.1},
   {'run_name': '{family}_joint_lowreg_5e4_wd5e4',
    'lr': 0.0005,
    'weight_decay': 0.0005,
    'max_epochs': 80,
    'patience': 15,
    'grad_clip_norm': 1.0,
    'dropout': 0.1}],
  'multitask': [{'run_name': '{family}_mt_base_2e3_wd1e4',
    'lr': 0.002,
    'weight_decay': 0.0001,
    'max_epochs': 30,
    'patience': 5,
    'grad_clip_norm': 1.0,
    'dropout': 0.1},
   {'run_name': '{family}_mt_stable_1e3_wd1e4',
    'lr': 0.001,
    'weight_decay': 0.0001,
    'max_epochs': 50,
    'patience': 10,
    'grad_clip_norm': 1.0,
    'dropout': 0.1},
   {'run_name': '{family}_mt_reg_1e3_wd5e4',
    'lr': 0.001,
    'weight_decay': 0.0005,
    'max_epochs': 50,
    'patience': 10,
    'grad_clip_norm': 1.0,
    'dropout': 0.1},
   {'run_name': '{family}_mt_low_5e4_wd1e4',
    'lr': 0.0005,
    'weight_decay': 0.0001,
    'max_epochs': 60,
    'patience': 12,
    'grad_clip_norm': 1.0,
    'dropout': 0.1},
   {'run_name': '{family}_mt_lowreg_5e4_wd5e4',
    'lr': 0.0005,
    'weight_decay': 0.0005,
    'max_epochs': 80,
    'patience': 15,
    'grad_clip_norm': 1.0,
    'dropout': 0.1}],
  'coordinate': [{'run_name': '{family}_coord_base_2e3_wd1e4',
    'lr': 0.002,
    'weight_decay': 0.0001,
    'max_epochs': 30,
    'patience': 5,
    'grad_clip_norm': 1.0,
    'dropout': 0.1},
   {'run_name': '{family}_coord_stable_1e3_wd1e4',
    'lr': 0.001,
    'weight_decay': 0.0001,
    'max_epochs': 50,
    'patience': 10,
    'grad_clip_norm': 1.0,
    'dropout': 0.1},
   {'run_name': '{family}_coord_reg_1e3_wd5e4',
    'lr': 0.001,
    'weight_decay': 0.0005,
    'max_epochs': 50,
    'patience': 10,
    'grad_clip_norm': 1.0,
    'dropout': 0.1},
   {'run_name': '{family}_coord_low_5e4_wd1e4',
    'lr': 0.0005,
    'weight_decay': 0.0001,
    'max_epochs': 60,
    'patience': 12,
    'grad_clip_norm': 1.0,
    'dropout': 0.1},
   {'run_name': '{family}_coord_lowreg_5e4_wd5e4',
    'lr': 0.0005,
    'weight_decay': 0.0005,
    'max_epochs': 80,
    'patience': 15,
    'grad_clip_norm': 1.0,
    'dropout': 0.1}]})

## Run Transformer tuning

In [9]:
RUN_GRID = True
GRID_SEED = 42

all_results = []

if RUN_GRID:
    for family in ["standard", "set"]:
        for task_name, trials in TRANSFORMER_GRIDS.items():
            y_train, y_val = task_data(task_name)
            print(f"\n===== {family.upper()} Transformer tuning: {task_name} =====")
            for raw_spec in trials:
                spec = dict(raw_spec)
                spec["run_name"] = spec["run_name"].format(family=family)
                dropout = float(spec.pop("dropout"))
                print(f"\n--- {spec['run_name']} ---")

                set_seed(GRID_SEED)
                model = build_model(family, task_name, dropout=dropout)
                cfg = make_cfg(**spec)
                row = run_trial(model, y_train, y_val, cfg, family=family, task=task_name, seed=GRID_SEED)
                row["dropout"] = dropout
                row["params"] = count_trainable_params(model)

                if family == "standard":
                    row.update(STANDARD_ARCH)
                else:
                    row.update(SET_ARCH)

                all_results.append(row)

transformer_tuning_df = pd.DataFrame(all_results)
transformer_tuning_df

===== STANDARD Transformer tuning: joint =====

--- standard_joint_base_2e3_wd1e4 ---
epoch=001 train_loss=2.4847 val_loss=2.1345 score=0.1278
epoch=005 train_loss=0.5267 val_loss=0.4715 score=0.8074
epoch=010 train_loss=0.3234 val_loss=0.4358 score=0.8686

--- standard_joint_stable_1e3_wd1e4 ---
epoch=001 train_loss=2.4429 val_loss=2.4289 score=0.1962
epoch=005 train_loss=0.6806 val_loss=0.8275 score=0.7111
epoch=010 train_loss=0.2854 val_loss=0.3170 score=0.9181
epoch=015 train_loss=0.1224 val_loss=0.4099 score=0.9001
epoch=020 train_loss=0.0837 val_loss=0.4482 score=0.9001
epoch=025 train_loss=0.0583 val_loss=0.2579 score=0.9487
epoch=030 train_loss=0.0296 val_loss=0.2963 score=0.9505

--- standard_joint_reg_1e3_wd5e4 ---
epoch=001 train_loss=2.4362 val_loss=1.8737 score=0.2610
epoch=005 train_loss=0.6559 val_loss=0.7568 score=0.6751
epoch=010 train_loss=0.3997 val_loss=0.6895 score=0.7075
epoch=015 train_loss=0.1520 val_loss=0.2684 score=0.9397
epoch=020 train_loss=0.1211 val_loss=0.3319 score=0.9334
epoch=025 train_loss=0.0485 val_loss=0.2955 score=0.9469
epoch=030 train_loss=0.0397 val_loss=0.4937 score=0.9118
epoch=035 train_loss=0.0261 val_loss=0.3512 score=0.9379

--- standard_joint_low_5e4_wd1e4 ---
epoch=001 train_loss=2.5236 val_loss=2.6648 score=0.0360
epoch=005 train_loss=1.1609 val_loss=1.0978 score=0.5590
epoch=010 train_loss=0.3577 val_loss=0.3989 score=0.8758
epoch=015 train_loss=0.1154 val_loss=0.2577 score=0.9370
epoch=020 train_loss=0.0764 val_loss=0.3458 score=0.9181
epoch=025 train_loss=0.0505 val_loss=0.3228 score=0.9298
epoch=030 train_loss=0.0398 val_loss=0.3530 score=0.9226
epoch=035 train_loss=0.0305 val_loss=0.3309 score=0.9316

--- standard_joint_lowreg_5e4_wd5e4 ---
epoch=001 train_loss=2.5236 val_loss=2.6648 score=0.0360
epoch=005 train_loss=1.0674 val_loss=1.0840 score=0.6103
epoch=010 train_loss=0.3120 val_loss=0.4018 score=0.8767
epoch=015 train_loss=0.1170 val_loss=0.3011 score=0.9244
epoch=020 train_loss=0.0675 val_loss=0.2793 score=0.9361
epoch=025 train_loss=0.0549 val_loss=0.2637 score=0.9469
epoch=030 train_loss=0.0405 val_loss=0.2726 score=0.9460
epoch=035 train_loss=0.0283 val_loss=0.3128 score=0.9370
epoch=040 train_loss=0.0186 val_loss=0.3245 score=0.9370

===== STANDARD Transformer tuning: multitask =====

--- standard_mt_base_2e3_wd1e4 ---
epoch=001 train_loss=2.5569 val_loss=2.0777 score=0.1017
epoch=005 train_loss=0.5924 val_loss=0.7949 score=0.7678
epoch=010 train_loss=0.0899 val_loss=0.2732 score=0.9433
epoch=015 train_loss=0.0457 val_loss=0.2951 score=0.9415

--- standard_mt_stable_1e3_wd1e4 ---
epoch=001 train_loss=2.4844 val_loss=2.0764 score=0.1224
epoch=005 train_loss=0.7611 val_loss=0.6694 score=0.7147
epoch=010 train_loss=0.3471 val_loss=0.3604 score=0.8911
epoch=015 train_loss=0.1758 val_loss=0.4241 score=0.8947
epoch=020 train_loss=0.1123 val_loss=0.2908 score=0.9325
epoch=025 train_loss=0.1078 val_loss=0.3064 score=0.9415
epoch=030 train_loss=0.0536 val_loss=0.2274 score=0.9577
epoch=035 train_loss=0.0552 val_loss=0.3338 score=0.9361
epoch=040 train_loss=0.0377 val_loss=0.2800 score=0.9487

--- standard_mt_reg_1e3_wd5e4 ---
epoch=001 train_loss=2.4845 val_loss=2.0843 score=0.1206
epoch=005 train_loss=0.7603 val_loss=0.6250 score=0.7345
epoch=010 train_loss=0.3739 val_loss=0.3639 score=0.8803
epoch=015 train_loss=0.2254 val_loss=0.2889 score=0.9280
epoch=020 train_loss=0.1120 val_loss=0.2668 score=0.9388
epoch=025 train_loss=0.0814 val_loss=0.2555 score=0.9451
epoch=030 train_loss=0.0638 val_loss=0.2330 score=0.9514
epoch=035 train_loss=0.0418 val_loss=0.2965 score=0.9415

--- standard_mt_low_5e4_wd1e4 ---
epoch=001 train_loss=2.5654 val_loss=2.4381 score=0.1350
epoch=005 train_loss=1.0689 val_loss=0.9247 score=0.5914
epoch=010 train_loss=0.5521 val_loss=0.4343 score=0.8605
epoch=015 train_loss=0.1598 val_loss=0.3237 score=0.9127
epoch=020 train_loss=0.0670 val_loss=0.2553 score=0.9370
epoch=025 train_loss=0.0594 val_loss=0.3067 score=0.9262
epoch=030 train_loss=0.0438 val_loss=0.2743 score=0.9397

--- standard_mt_lowreg_5e4_wd5e4 ---
epoch=001 train_loss=2.5654 val_loss=2.4400 score=0.1350
epoch=005 train_loss=0.9316 val_loss=0.9937 score=0.5563
epoch=010 train_loss=0.5959 val_loss=0.7684 score=0.6679
epoch=015 train_loss=0.1663 val_loss=0.2654 score=0.9307
epoch=020 train_loss=0.0991 val_loss=0.3171 score=0.9172
epoch=025 train_loss=0.0884 val_loss=0.2964 score=0.9334
epoch=030 train_loss=0.0455 val_loss=0.2404 score=0.9478
epoch=035 train_loss=0.0344 val_loss=0.2598 score=0.9442
epoch=040 train_loss=0.0291 val_loss=0.2641 score=0.9451

===== STANDARD Transformer tuning: coordinate =====

--- standard_coord_base_2e3_wd1e4 ---
epoch=001 train_loss=1.0240 val_loss=1.2642 score=-142.6447
epoch=005 train_loss=0.0682 val_loss=0.0614 score=-28.9326
epoch=010 train_loss=0.0246 val_loss=0.0308 score=-18.3587
epoch=015 train_loss=0.0176 val_loss=0.0184 score=-14.4996
epoch=020 train_loss=0.0141 val_loss=0.0182 score=-12.5306
epoch=025 train_loss=0.0129 val_loss=0.0120 score=-11.0146

--- standard_coord_stable_1e3_wd1e4 ---
epoch=001 train_loss=0.8530 val_loss=0.2810 score=-60.0413
epoch=005 train_loss=0.0516 val_loss=0.0333 score=-19.3080
epoch=010 train_loss=0.0182 val_loss=0.0219 score=-16.7357
epoch=015 train_loss=0.0155 val_loss=0.0149 score=-11.8808
epoch=020 train_loss=0.0137 val_loss=0.0139 score=-10.6592
epoch=025 train_loss=0.0130 val_loss=0.0129 score=-10.2789
epoch=030 train_loss=0.0122 val_loss=0.0136 score=-10.8177
epoch=035 train_loss=0.0112 val_loss=0.0127 score=-10.0884
epoch=040 train_loss=0.0112 val_loss=0.0129 score=-10.1432
epoch=045 train_loss=0.0106 val_loss=0.0127 score=-10.1720
epoch=050 train_loss=0.0104 val_loss=0.0127 score=-10.1942

--- standard_coord_reg_1e3_wd5e4 ---
epoch=001 train_loss=0.8530 val_loss=0.2810 score=-60.0407
epoch=005 train_loss=0.0574 val_loss=0.0395 score=-22.6242
epoch=010 train_loss=0.0191 val_loss=0.0204 score=-15.9949
epoch=015 train_loss=0.0157 val_loss=0.0145 score=-11.9508
epoch=020 train_loss=0.0137 val_loss=0.0140 score=-10.7378
epoch=025 train_loss=0.0130 val_loss=0.0133 score=-10.8727
epoch=030 train_loss=0.0118 val_loss=0.0132 score=-10.4580
epoch=035 train_loss=0.0115 val_loss=0.0131 score=-10.1577
epoch=040 train_loss=0.0115 val_loss=0.0140 score=-10.4553
epoch=045 train_loss=0.0108 val_loss=0.0133 score=-10.3621

--- standard_coord_low_5e4_wd1e4 ---
epoch=001 train_loss=0.8957 val_loss=0.3560 score=-68.7011
epoch=005 train_loss=0.0733 val_loss=0.0553 score=-29.2630
epoch=010 train_loss=0.0226 val_loss=0.0153 score=-12.5364
epoch=015 train_loss=0.0175 val_loss=0.0149 score=-12.0172
epoch=020 train_loss=0.0148 val_loss=0.0144 score=-11.2876
epoch=025 train_loss=0.0141 val_loss=0.0140 score=-11.3165
epoch=030 train_loss=0.0128 val_loss=0.0160 score=-11.9145
epoch=035 train_loss=0.0121 val_loss=0.0147 score=-10.9679
epoch=040 train_loss=0.0115 val_loss=0.0155 score=-11.1379
epoch=045 train_loss=0.0112 val_loss=0.0150 score=-10.9000
epoch=050 train_loss=0.0110 val_loss=0.0147 score=-10.9434

--- standard_coord_lowreg_5e4_wd5e4 ---
epoch=001 train_loss=0.8957 val_loss=0.3541 score=-68.5000
epoch=005 train_loss=0.0705 val_loss=0.0416 score=-23.4423
epoch=010 train_loss=0.0231 val_loss=0.0149 score=-12.4828
epoch=015 train_loss=0.0181 val_loss=0.0151 score=-12.3070
epoch=020 train_loss=0.0151 val_loss=0.0141 score=-11.2739
epoch=025 train_loss=0.0142 val_loss=0.0132 score=-10.8621
epoch=030 train_loss=0.0130 val_loss=0.0154 score=-11.7338
epoch=035 train_loss=0.0122 val_loss=0.0146 score=-11.1189
epoch=040 train_loss=0.0118 val_loss=0.0146 score=-11.1915
epoch=045 train_loss=0.0116 val_loss=0.0147 score=-11.2600
epoch=050 train_loss=0.0115 val_loss=0.0144 score=-11.3395
epoch=055 train_loss=0.0112 val_loss=0.0138 score=-10.8373
epoch=060 train_loss=0.0113 val_loss=0.0141 score=-11.0731
epoch=065 train_loss=0.0112 val_loss=0.0142 score=-10.9895
epoch=070 train_loss=0.0111 val_loss=0.0139 score=-10.7818
epoch=075 train_loss=0.0109 val_loss=0.0139 score=-10.6929

===== SET Transformer tuning: joint =====

--- set_joint_base_2e3_wd1e4 ---
epoch=001 train_loss=2.5317 val_loss=2.6080 score=0.0360
epoch=005 train_loss=2.5255 val_loss=2.6015 score=0.0360

--- set_joint_stable_1e3_wd1e4 ---
epoch=001 train_loss=2.5031 val_loss=2.4005 score=0.0909
epoch=005 train_loss=0.6990 val_loss=0.6460 score=0.7939
epoch=010 train_loss=0.3666 val_loss=0.4189 score=0.8920
epoch=015 train_loss=0.2172 val_loss=0.6857 score=0.8245
epoch=020 train_loss=0.1165 val_loss=0.9036 score=0.7750
epoch=025 train_loss=0.0492 val_loss=0.4128 score=0.9190
epoch=030 train_loss=0.0302 val_loss=0.4833 score=0.9064

--- set_joint_reg_1e3_wd5e4 ---
epoch=001 train_loss=2.5033 val_loss=2.4095 score=0.0891
epoch=005 train_loss=0.7722 val_loss=0.7658 score=0.6472
epoch=010 train_loss=0.3774 val_loss=0.3704 score=0.9109
epoch=015 train_loss=0.2419 val_loss=0.4255 score=0.9172
epoch=020 train_loss=0.1305 val_loss=0.4237 score=0.9280
epoch=025 train_loss=0.0866 val_loss=0.4724 score=0.9217
epoch=030 train_loss=0.0546 val_loss=0.5091 score=0.9172

--- set_joint_low_5e4_wd1e4 ---
epoch=001 train_loss=2.5041 val_loss=2.6710 score=0.0981
epoch=005 train_loss=1.0603 val_loss=1.1493 score=0.4491
epoch=010 train_loss=0.7119 val_loss=0.9273 score=0.6265
epoch=015 train_loss=0.2417 val_loss=0.3783 score=0.8875
epoch=020 train_loss=0.1407 val_loss=0.2501 score=0.9388
epoch=025 train_loss=0.0939 val_loss=0.4843 score=0.8902
epoch=030 train_loss=0.0634 val_loss=0.3133 score=0.9325

--- set_joint_lowreg_5e4_wd5e4 ---
epoch=001 train_loss=2.5041 val_loss=2.6689 score=0.0954
epoch=005 train_loss=1.1624 val_loss=1.0694 score=0.5527
epoch=010 train_loss=0.6818 val_loss=0.6754 score=0.7741
epoch=015 train_loss=0.2333 val_loss=0.3598 score=0.8992
epoch=020 train_loss=0.1454 val_loss=0.3538 score=0.9199
epoch=025 train_loss=0.0700 val_loss=0.3771 score=0.9199
epoch=030 train_loss=0.0634 val_loss=0.4103 score=0.9181
epoch=035 train_loss=0.0513 val_loss=0.4073 score=0.9235
epoch=040 train_loss=0.0385 val_loss=0.3617 score=0.9307
epoch=045 train_loss=0.0296 val_loss=0.3880 score=0.9253
epoch=050 train_loss=0.0232 val_loss=0.3732 score=0.9316
epoch=055 train_loss=0.0194 val_loss=0.3773 score=0.9388

===== SET Transformer tuning: multitask =====

--- set_mt_base_2e3_wd1e4 ---
epoch=001 train_loss=2.5913 val_loss=2.6567 score=0.0999
epoch=005 train_loss=1.9494 val_loss=1.9993 score=0.2205
epoch=010 train_loss=1.9056 val_loss=2.0331 score=0.1818

--- set_mt_stable_1e3_wd1e4 ---
epoch=001 train_loss=2.5879 val_loss=2.6614 score=0.1071
epoch=005 train_loss=0.8345 val_loss=0.9680 score=0.6031
epoch=010 train_loss=0.3504 val_loss=0.8552 score=0.7183
epoch=015 train_loss=0.1654 val_loss=0.5632 score=0.8515
epoch=020 train_loss=0.0973 val_loss=0.4273 score=0.9073
epoch=025 train_loss=0.0764 val_loss=1.1791 score=0.7570
epoch=030 train_loss=0.0551 val_loss=0.4023 score=0.9217
epoch=035 train_loss=0.0406 val_loss=0.5591 score=0.9046
epoch=040 train_loss=0.0231 val_loss=0.4489 score=0.9361

--- set_mt_reg_1e3_wd5e4 ---
epoch=001 train_loss=2.5879 val_loss=2.6614 score=0.1071
epoch=005 train_loss=0.8348 val_loss=0.8883 score=0.6364
epoch=010 train_loss=0.4013 val_loss=0.5219 score=0.8389
epoch=015 train_loss=0.2581 val_loss=0.4310 score=0.8884
epoch=020 train_loss=0.0916 val_loss=0.4053 score=0.9154
epoch=025 train_loss=0.0851 val_loss=0.4598 score=0.9127
epoch=030 train_loss=0.0496 val_loss=0.6163 score=0.8848

--- set_mt_low_5e4_wd1e4 ---
epoch=001 train_loss=2.5585 val_loss=3.0396 score=0.0801
epoch=005 train_loss=1.2423 val_loss=1.8156 score=0.2034
epoch=010 train_loss=0.6281 val_loss=0.6114 score=0.8029
epoch=015 train_loss=0.5205 val_loss=0.4822 score=0.8614
epoch=020 train_loss=0.2718 val_loss=0.3559 score=0.9100
epoch=025 train_loss=0.0996 val_loss=0.4708 score=0.8848
epoch=030 train_loss=0.0604 val_loss=0.2759 score=0.9442
epoch=035 train_loss=0.0441 val_loss=0.3801 score=0.9280
epoch=040 train_loss=0.0256 val_loss=0.3640 score=0.9352

--- set_mt_lowreg_5e4_wd5e4 ---
epoch=001 train_loss=2.5584 val_loss=3.0424 score=0.0783
epoch=005 train_loss=1.1720 val_loss=1.1219 score=0.4932
epoch=010 train_loss=0.7349 val_loss=0.6124 score=0.7867
epoch=015 train_loss=0.2509 val_loss=0.3821 score=0.8731
epoch=020 train_loss=0.1201 val_loss=0.2250 score=0.9370
epoch=025 train_loss=0.0921 val_loss=0.2957 score=0.9262
epoch=030 train_loss=0.0421 val_loss=0.3068 score=0.9325
epoch=035 train_loss=0.0333 val_loss=0.2471 score=0.9523
epoch=040 train_loss=0.0270 val_loss=0.2969 score=0.9451
epoch=045 train_loss=0.0228 val_loss=0.2698 score=0.9478
epoch=050 train_loss=0.0213 val_loss=0.2655 score=0.9523

===== SET Transformer tuning: coordinate =====

--- set_coord_base_2e3_wd1e4 ---
epoch=001 train_loss=0.5383 val_loss=0.1790 score=-48.1755
epoch=005 train_loss=0.0536 val_loss=0.0547 score=-26.1045
epoch=010 train_loss=0.0214 val_loss=0.0254 score=-16.3162
epoch=015 train_loss=0.0149 val_loss=0.0203 score=-14.8494
epoch=020 train_loss=0.0129 val_loss=0.0141 score=-12.3281
epoch=025 train_loss=0.0123 val_loss=0.0176 score=-12.9995

--- set_coord_stable_1e3_wd1e4 ---
epoch=001 train_loss=0.6234 val_loss=0.2001 score=-48.9260
epoch=005 train_loss=0.0658 val_loss=0.0556 score=-26.5764
epoch=010 train_loss=0.0193 val_loss=0.0175 score=-13.5325
epoch=015 train_loss=0.0148 val_loss=0.0173 score=-14.2852
epoch=020 train_loss=0.0132 val_loss=0.0147 score=-11.8873
epoch=025 train_loss=0.0116 val_loss=0.0149 score=-11.9145
epoch=030 train_loss=0.0110 val_loss=0.0156 score=-12.1652
epoch=035 train_loss=0.0107 val_loss=0.0153 score=-12.0703
epoch=040 train_loss=0.0104 val_loss=0.0154 score=-11.5461
epoch=045 train_loss=0.0099 val_loss=0.0149 score=-11.6127

--- set_coord_reg_1e3_wd5e4 ---
epoch=001 train_loss=0.6240 val_loss=0.2178 score=-50.9434
epoch=005 train_loss=0.0665 val_loss=0.0654 score=-29.6377
epoch=010 train_loss=0.0194 val_loss=0.0187 score=-14.3379
epoch=015 train_loss=0.0149 val_loss=0.0170 score=-13.9878
epoch=020 train_loss=0.0132 val_loss=0.0151 score=-12.1393
epoch=025 train_loss=0.0117 val_loss=0.0150 score=-12.1671
epoch=030 train_loss=0.0110 val_loss=0.0155 score=-12.3121
epoch=035 train_loss=0.0107 val_loss=0.0149 score=-12.2240
epoch=040 train_loss=0.0104 val_loss=0.0143 score=-11.4285
epoch=045 train_loss=0.0100 val_loss=0.0142 score=-11.5515

--- set_coord_low_5e4_wd1e4 ---
epoch=001 train_loss=0.8092 val_loss=0.4006 score=-71.9926
epoch=005 train_loss=0.0926 val_loss=0.0657 score=-29.0098
epoch=010 train_loss=0.0319 val_loss=0.0241 score=-16.9394
epoch=015 train_loss=0.0191 val_loss=0.0187 score=-15.2070
epoch=020 train_loss=0.0149 val_loss=0.0159 score=-12.6913
epoch=025 train_loss=0.0142 val_loss=0.0167 score=-13.1640
epoch=030 train_loss=0.0134 val_loss=0.0162 score=-13.2027
epoch=035 train_loss=0.0132 val_loss=0.0152 score=-12.3416
epoch=040 train_loss=0.0127 val_loss=0.0153 score=-12.0775
epoch=045 train_loss=0.0125 val_loss=0.0153 score=-12.2913
epoch=050 train_loss=0.0124 val_loss=0.0154 score=-12.3595

--- set_coord_lowreg_5e4_wd5e4 ---
epoch=001 train_loss=0.8014 val_loss=0.6605 score=-93.1413
epoch=005 train_loss=0.0833 val_loss=0.0640 score=-28.7117
epoch=010 train_loss=0.0302 val_loss=0.0260 score=-18.2252
epoch=015 train_loss=0.0193 val_loss=0.0173 score=-14.2104
epoch=020 train_loss=0.0152 val_loss=0.0160 score=-12.7579
epoch=025 train_loss=0.0143 val_loss=0.0180 score=-13.8523
epoch=030 train_loss=0.0135 val_loss=0.0166 score=-13.5592
epoch=035 train_loss=0.0134 val_loss=0.0161 score=-13.0389
epoch=040 train_loss=0.0127 val_loss=0.0155 score=-12.4213
epoch=045 train_loss=0.0124 val_loss=0.0152 score=-12.3719
epoch=050 train_loss=0.0123 val_loss=0.0154 score=-12.5012

,family,task,run_name,seed,lr,weight_decay,batch_size,val_batch_size,max_epochs,patience,print_every,grad_clip_norm,best_epoch,epoch,train_loss,val_loss,score,joint_accuracy,building_accuracy,floor_accuracy,dropout,params,d_model,nhead,num_layers,dim_feedforward,coordinate_mean_euclidean,coordinate_rmse,coordinate_mean_euclidean_m,coordinate_rmse_m,num_heads,num_sab_layers,num_seed_vectors
0,standard,joint,standard_joint_base_2e3_wd1e4,42,0.0020,0.0001,256,512,30,5,5,1.0,7,7.0,0.384609,0.348302,0.915392,0.915392,0.997300,0.917192,0.1,350861,128,4.0,2.0,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,standard,joint,standard_joint_stable_1e3_wd1e4,42,0.0010,0.0001,256,512,50,10,5,1.0,23,23.0,0.076801,0.282502,0.950495,0.950495,1.000000,0.950495,0.1,350861,128,4.0,2.0,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,standard,joint,standard_joint_reg_1e3_wd5e4,42,0.0010,0.0005,256,512,50,10,5,1.0,29,29.0,0.035338,0.304360,0.950495,0.950495,1.000000,0.950495,0.1,350861,128,4.0,2.0,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,standard,joint,standard_joint_low_5e4_wd1e4,42,0.0005,0.0001,256,512,60,12,5,1.0,26,26.0,0.044039,0.291321,0.942394,0.942394,0.999100,0.943294,0.1,350861,128,4.0,2.0,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,standard,joint,standard_joint_lowreg_5e4_wd5e4,42,0.0005,0.0005,256,512,80,15,5,1.0,25,25.0,0.054921,0.263657,0.946895,0.946895,0.999100,0.946895,0.1,350861,128,4.0,2.0,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,standard,multitask,standard_mt_base_2e3_wd1e4,42,0.0020,0.0001,256,512,30,5,5,1.0,14,14.0,0.059586,0.247015,0.955896,0.955896,0.994599,0.956796,0.1,366728,128,4.0,2.0,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,standard,multitask,standard_mt_stable_1e3_wd1e4,42,0.0010,0.0001,256,512,50,10,5,1.0,30,30.0,0.053569,0.227362,0.957696,0.957696,0.999100,0.957696,0.1,366728,128,4.0,2.0,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,standard,multitask,standard_mt_reg_1e3_wd5e4,42,0.0010,0.0005,256,512,50,10,5,1.0,28,28.0,0.064521,0.244919,0.954095,0.954095,0.999100,0.954095,0.1,366728,128,4.0,2.0,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,standard,multitask,standard_mt_low_5e4_wd1e4,42,0.0005,0.0001,256,512,60,12,5,1.0,22,22.0,0.073655,0.240674,0.944194,0.944194,0.995500,0.946895,0.1,366728,128,4.0,2.0,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,standard,multitask,standard_mt_lowreg_5e4_wd5e4,42,0.0005,0.0005,256,512,80,15,5,1.0,27,27.0,0.056854,0.226731,0.952295,0.952295,0.996400,0.955896,0.1,366728,128,4.0,2.0,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,standard,coordinate,standard_coord_base_2e3_wd1e4,42,0.0020,0.0001,256,512,30,5,5,1.0,22,22.0,0.013525,0.011712,-10.691304,NaN,NaN,NaN,0.1,349442,128,4.0,2.0,256,0.119500,0.152394,10.691304,13.548611,NaN,NaN,NaN
11,standard,coordinate,standard_coord_stable_1e3_wd1e4,42,0.0010,0.0001,256,512,50,10,5,1.0,48,48.0,0.010434,0.012527,-9.980649,NaN,NaN,NaN,0.1,349442,128,4.0,2.0,256,0.114569,0.154306,9.980649,13.165650,NaN,NaN,NaN
12,standard,coordinate,standard_coord_reg_1e3_wd5e4,42,0.0010,0.0005,256,512,50,10,5,1.0,35,35.0,0.011512,0.013116,-10.157655,NaN,NaN,NaN,0.1,349442,128,4.0,2.0,256,0.116780,0.157691,10.157655,13.507136,NaN,NaN,NaN
13,standard,coordinate,standard_coord_low_5e4_wd1e4,42,0.0005,0.0001,256,512,60,12,5,1.0,41,41.0,0.011396,0.014429,-10.647083,NaN,NaN,NaN,0.1,349442,128,4.0,2.0,256,0.121901,0.165753,10.647083,14.325345,NaN,NaN,NaN
14,standard,coordinate,standard_coord_lowreg_5e4_wd5e4,42,0.0005,0.0005,256,512,80,15,5,1.0,64,64.0,0.011060,0.013829,-10.631206,NaN,NaN,NaN,0.1,349442,128,4.0,2.0,256,0.121107,0.162796,10.631206,14.186916,NaN,NaN,NaN
15,set,joint,set_joint_base_2e3_wd1e4,42,0.0020,0.0001,256,512,30,5,5,1.0,1,1.0,2.531709,2.608020,0.036004,0.036004,0.241224,0.154815,0.1,483213,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0,1.0
16,set,joint,set_joint_stable_1e3_wd1e4,42,0.0010,0.0001,256,512,50,10,5,1.0,24,24.0,0.051124,0.376869,0.924392,0.924392,0.996400,0.924392,0.1,483213,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0,1.0
17,set,joint,set_joint_reg_1e3_wd5e4,42,0.0010,0.0005,256,512,50,10,5,1.0,20,20.0,0.130466,0.423695,0.927993,0.927993,0.999100,0.927993,0.1,483213,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0,1.0
18,set,joint,set_joint_low_5e4_wd1e4,42,0.0005,0.0001,256,512,60,12,5,1.0,20,20.0,0.140748,0.250050,0.938794,0.938794,0.999100,0.938794,0.1,483213,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0,1.0
19,set,joint,set_joint_lowreg_5e4_wd5e4,42,0.0005,0.0005,256,512,80,15,5,1.0,43,43.0,0.034788,0.337773,0.944194,0.944194,0.999100,0.944194,0.1,483213,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0,1.0
20,set,multitask,set_mt_base_2e3_wd1e4,42,0.0020,0.0001,256,512,30,5,5,1.0,5,5.0,1.949404,1.999314,0.220522,0.220522,0.719172,0.349235,0.1,499080,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0,1.0
21,set,multitask,set_mt_stable_1e3_wd1e4,42,0.0010,0.0001,256,512,50,10,5,1.0,32,32.0,0.058961,0.364586,0.945095,0.945095,0.994599,0.945995,0.1,499080,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0,1.0
22,set,multitask,set_mt_reg_1e3_wd5e4,42,0.0010,0.0005,256,512,50,10,5,1.0,21,21.0,0.090662,0.362196,0.933393,0.933393,0.998200,0.935194,0.1,499080,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0,1.0
23,set,multitask,set_mt_low_5e4_wd1e4,42,0.0005,0.0001,256,512,60,12,5,1.0,30,30.0,0.060439,0.275943,0.944194,0.944194,0.995500,0.947795,0.1,499080,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0,1.0
24,set,multitask,set_mt_lowreg_5e4_wd5e4,42,0.0005,0.0005,256,512,80,15,5,1.0,38,38.0,0.030049,0.228611,0.955896,0.955896,0.998200,0.956796,0.1,499080,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0,1.0
25,set,coordinate,set_coord_base_2e3_wd1e4,42,0.0020,0.0001,256,512,30,5,5,1.0,22,22.0,0.013275,0.015951,-11.658532,NaN,NaN,NaN,0.1,481794,128,NaN,NaN,256,0.132199,0.178512,11.658532,15.524725,4.0,2.0,1.0
26,set,coordinate,set_coord_stable_1e3_wd1e4,42,0.0010,0.0001,256,512,50,10,5,1.0,37,37.0,0.010546,0.013888,-10.921133,NaN,NaN,NaN,0.1,481794,128,NaN,NaN,256,0.123511,0.164046,10.921133,14.142971,4.0,2.0,1.0
27,set,coordinate,set_coord_reg_1e3_wd5e4,42,0.0010,0.0005,256,512,50,10,5,1.0,37,37.0,0.010662,0.013415,-10.919728,NaN,NaN,NaN,0.1,481794,128,NaN,NaN,256,0.123422,0.162111,10.919728,14.040860,4.0,2.0,1.0
28,set,coordinate,set_coord_low_5e4_wd1e4,42,0.0005,0.0001,256,512,60,12,5,1.0,39,39.0,0.012688,0.014808,-11.804937,NaN,NaN,NaN,0.1,481794,128,NaN,NaN,256,0.132984,0.170866,11.804937,14.679612,4.0,2.0,1.0
29,set,coordinate,set_coord_lowreg_5e4_wd5e4,42,0.0005,0.0005,256,512,80,15,5,1.0,39,39.0,0.012681,0.015213,-12.127828,NaN,NaN,NaN,0.1,481794,128,NaN,NaN,256,0.136194,0.173457,12.127828,14.925200,4.0,2.0,1.0

## Select best candidate per family/task

In [10]:
summary_cols = [
    "family", "task", "run_name", "seed", "best_epoch", "score",
    "joint_accuracy", "building_accuracy", "floor_accuracy",
    "coordinate_mean_euclidean_m", "coordinate_rmse_m",
    "lr", "weight_decay", "dropout", "max_epochs", "patience", "grad_clip_norm", "params",
    "d_model", "nhead", "num_layers", "num_heads", "num_sab_layers", "dim_feedforward", "num_seed_vectors"
]

display(transformer_tuning_df[[c for c in summary_cols if c in transformer_tuning_df.columns]].sort_values(["family", "task", "score"], ascending=[True, True, False]))

best_by_family_task = (
    transformer_tuning_df
    .sort_values(["family", "task", "score"], ascending=[True, True, False])
    .groupby(["family", "task"], as_index=False)
    .first()
)

best_by_family_task

,family,task,run_name,seed,best_epoch,score,joint_accuracy,building_accuracy,floor_accuracy,coordinate_mean_euclidean_m,coordinate_rmse_m,lr,weight_decay,dropout,max_epochs,patience,grad_clip_norm,params,d_model,nhead,num_layers,num_heads,num_sab_layers,dim_feedforward,num_seed_vectors
27,set,coordinate,set_coord_reg_1e3_wd5e4,42,37,-10.919728,NaN,NaN,NaN,10.919728,14.040860,0.0010,0.0005,0.1,50,10,1.0,481794,128,NaN,NaN,4.0,2.0,256,1.0
26,set,coordinate,set_coord_stable_1e3_wd1e4,42,37,-10.921133,NaN,NaN,NaN,10.921133,14.142971,0.0010,0.0001,0.1,50,10,1.0,481794,128,NaN,NaN,4.0,2.0,256,1.0
25,set,coordinate,set_coord_base_2e3_wd1e4,42,22,-11.658532,NaN,NaN,NaN,11.658532,15.524725,0.0020,0.0001,0.1,30,5,1.0,481794,128,NaN,NaN,4.0,2.0,256,1.0
28,set,coordinate,set_coord_low_5e4_wd1e4,42,39,-11.804937,NaN,NaN,NaN,11.804937,14.679612,0.0005,0.0001,0.1,60,12,1.0,481794,128,NaN,NaN,4.0,2.0,256,1.0
29,set,coordinate,set_coord_lowreg_5e4_wd5e4,42,39,-12.127828,NaN,NaN,NaN,12.127828,14.925200,0.0005,0.0005,0.1,80,15,1.0,481794,128,NaN,NaN,4.0,2.0,256,1.0
19,set,joint,set_joint_lowreg_5e4_wd5e4,42,43,0.944194,0.944194,0.999100,0.944194,NaN,NaN,0.0005,0.0005,0.1,80,15,1.0,483213,128,NaN,NaN,4.0,2.0,256,1.0
18,set,joint,set_joint_low_5e4_wd1e4,42,20,0.938794,0.938794,0.999100,0.938794,NaN,NaN,0.0005,0.0001,0.1,60,12,1.0,483213,128,NaN,NaN,4.0,2.0,256,1.0
17,set,joint,set_joint_reg_1e3_wd5e4,42,20,0.927993,0.927993,0.999100,0.927993,NaN,NaN,0.0010,0.0005,0.1,50,10,1.0,483213,128,NaN,NaN,4.0,2.0,256,1.0
16,set,joint,set_joint_stable_1e3_wd1e4,42,24,0.924392,0.924392,0.996400,0.924392,NaN,NaN,0.0010,0.0001,0.1,50,10,1.0,483213,128,NaN,NaN,4.0,2.0,256,1.0
15,set,joint,set_joint_base_2e3_wd1e4,42,1,0.036004,0.036004,0.241224,0.154815,NaN,NaN,0.0020,0.0001,0.1,30,5,1.0,483213,128,NaN,NaN,4.0,2.0,256,1.0
24,set,multitask,set_mt_lowreg_5e4_wd5e4,42,38,0.955896,0.955896,0.998200,0.956796,NaN,NaN,0.0005,0.0005,0.1,80,15,1.0,499080,128,NaN,NaN,4.0,2.0,256,1.0
21,set,multitask,set_mt_stable_1e3_wd1e4,42,32,0.945095,0.945095,0.994599,0.945995,NaN,NaN,0.0010,0.0001,0.1,50,10,1.0,499080,128,NaN,NaN,4.0,2.0,256,1.0
23,set,multitask,set_mt_low_5e4_wd1e4,42,30,0.944194,0.944194,0.995500,0.947795,NaN,NaN,0.0005,0.0001,0.1,60,12,1.0,499080,128,NaN,NaN,4.0,2.0,256,1.0
22,set,multitask,set_mt_reg_1e3_wd5e4,42,21,0.933393,0.933393,0.998200,0.935194,NaN,NaN,0.0010,0.0005,0.1,50,10,1.0,499080,128,NaN,NaN,4.0,2.0,256,1.0
20,set,multitask,set_mt_base_2e3_wd1e4,42,5,0.220522,0.220522,0.719172,0.349235,NaN,NaN,0.0020,0.0001,0.1,30,5,1.0,499080,128,NaN,NaN,4.0,2.0,256,1.0
11,standard,coordinate,standard_coord_stable_1e3_wd1e4,42,48,-9.980649,NaN,NaN,NaN,9.980649,13.165650,0.0010,0.0001,0.1,50,10,1.0,349442,128,4.0,2.0,NaN,NaN,256,NaN
12,standard,coordinate,standard_coord_reg_1e3_wd5e4,42,35,-10.157655,NaN,NaN,NaN,10.157655,13.507136,0.0010,0.0005,0.1,50,10,1.0,349442,128,4.0,2.0,NaN,NaN,256,NaN
14,standard,coordinate,standard_coord_lowreg_5e4_wd5e4,42,64,-10.631206,NaN,NaN,NaN,10.631206,14.186916,0.0005,0.0005,0.1,80,15,1.0,349442,128,4.0,2.0,NaN,NaN,256,NaN
13,standard,coordinate,standard_coord_low_5e4_wd1e4,42,41,-10.647083,NaN,NaN,NaN,10.647083,14.325345,0.0005,0.0001,0.1,60,12,1.0,349442,128,4.0,2.0,NaN,NaN,256,NaN
10,standard,coordinate,standard_coord_base_2e3_wd1e4,42,22,-10.691304,NaN,NaN,NaN,10.691304,13.548611,0.0020,0.0001,0.1,30,5,1.0,349442,128,4.0,2.0,NaN,NaN,256,NaN
2,standard,joint,standard_joint_reg_1e3_wd5e4,42,29,0.950495,0.950495,1.000000,0.950495,NaN,NaN,0.0010,0.0005,0.1,50,10,1.0,350861,128,4.0,2.0,NaN,NaN,256,NaN
1,standard,joint,standard_joint_stable_1e3_wd1e4,42,23,0.950495,0.950495,1.000000,0.950495,NaN,NaN,0.0010,0.0001,0.1,50,10,1.0,350861,128,4.0,2.0,NaN,NaN,256,NaN
4,standard,joint,standard_joint_lowreg_5e4_wd5e4,42,25,0.946895,0.946895,0.999100,0.946895,NaN,NaN,0.0005,0.0005,0.1,80,15,1.0,350861,128,4.0,2.0,NaN,NaN,256,NaN
3,standard,joint,standard_joint_low_5e4_wd1e4,42,26,0.942394,0.942394,0.999100,0.943294,NaN,NaN,0.0005,0.0001,0.1,60,12,1.0,350861,128,4.0,2.0,NaN,NaN,256,NaN
0,standard,joint,standard_joint_base_2e3_wd1e4,42,7,0.915392,0.915392,0.997300,0.917192,NaN,NaN,0.0020,0.0001,0.1,30,5,1.0,350861,128,4.0,2.0,NaN,NaN,256,NaN
6,standard,multitask,standard_mt_stable_1e3_wd1e4,42,30,0.957696,0.957696,0.999100,0.957696,NaN,NaN,0.0010,0.0001,0.1,50,10,1.0,366728,128,4.0,2.0,NaN,NaN,256,NaN
5,standard,multitask,standard_mt_base_2e3_wd1e4,42,14,0.955896,0.955896,0.994599,0.956796,NaN,NaN,0.0020,0.0001,0.1,30,5,1.0,366728,128,4.0,2.0,NaN,NaN,256,NaN
7,standard,multitask,standard_mt_reg_1e3_wd5e4,42,28,0.954095,0.954095,0.999100,0.954095,NaN,NaN,0.0010,0.0005,0.1,50,10,1.0,366728,128,4.0,2.0,NaN,NaN,256,NaN
9,standard,multitask,standard_mt_lowreg_5e4_wd5e4,42,27,0.952295,0.952295,0.996400,0.955896,NaN,NaN,0.0005,0.0005,0.1,80,15,1.0,366728,128,4.0,2.0,NaN,NaN,256,NaN
8,standard,multitask,standard_mt_low_5e4_wd1e4,42,22,0.944194,0.944194,0.995500,0.946895,NaN,NaN,0.0005,0.0001,0.1,60,12,1.0,366728,128,4.0,2.0,NaN,NaN,256,NaN

,family,task,run_name,seed,lr,weight_decay,batch_size,val_batch_size,max_epochs,patience,print_every,grad_clip_norm,best_epoch,epoch,train_loss,val_loss,score,joint_accuracy,building_accuracy,floor_accuracy,dropout,params,d_model,nhead,num_layers,dim_feedforward,coordinate_mean_euclidean,coordinate_rmse,coordinate_mean_euclidean_m,coordinate_rmse_m,num_heads,num_sab_layers,num_seed_vectors
0,set,coordinate,set_coord_reg_1e3_wd5e4,42,0.0010,0.0005,256,512,50,10,5,1.0,37,37.0,0.010662,0.013415,-10.919728,NaN,NaN,NaN,0.1,481794,128,NaN,NaN,256,0.123422,0.162111,10.919728,14.04086,4.0,2.0,1.0
1,set,joint,set_joint_lowreg_5e4_wd5e4,42,0.0005,0.0005,256,512,80,15,5,1.0,43,43.0,0.034788,0.337773,0.944194,0.944194,0.9991,0.944194,0.1,483213,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0,1.0
2,set,multitask,set_mt_lowreg_5e4_wd5e4,42,0.0005,0.0005,256,512,80,15,5,1.0,38,38.0,0.030049,0.228611,0.955896,0.955896,0.9982,0.956796,0.1,499080,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0,1.0
3,standard,coordinate,standard_coord_stable_1e3_wd1e4,42,0.0010,0.0001,256,512,50,10,5,1.0,48,48.0,0.010434,0.012527,-9.980649,NaN,NaN,NaN,0.1,349442,128,4.0,2.0,256,0.114569,0.154306,9.980649,13.16565,NaN,NaN,NaN
4,standard,joint,standard_joint_reg_1e3_wd5e4,42,0.0010,0.0005,256,512,50,10,5,1.0,29,29.0,0.035338,0.304360,0.950495,0.950495,1.0000,0.950495,0.1,350861,128,4.0,2.0,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,standard,multitask,standard_mt_stable_1e3_wd1e4,42,0.0010,0.0001,256,512,50,10,5,1.0,30,30.0,0.053569,0.227362,0.957696,0.957696,0.9991,0.957696,0.1,366728,128,4.0,2.0,256,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 3-seed confirmation for selected Transformer configs

In [11]:
RUN_CONFIRM_FINAL = True
SEEDS_CONFIRM = (42, 123, 999)

confirm_rows = []

if RUN_CONFIRM_FINAL:
    for _, best in best_by_family_task.iterrows():
        family = best["family"]
        task_name = best["task"]
        y_train, y_val = task_data(task_name)

        spec = {
            "run_name": f"confirm_{best['run_name']}",
            "lr": float(best["lr"]),
            "weight_decay": float(best["weight_decay"]),
            "max_epochs": int(best["max_epochs"]),
            "patience": int(best["patience"]),
            "print_every": 5,
            "grad_clip_norm": None if pd.isna(best.get("grad_clip_norm", None)) else float(best["grad_clip_norm"]),
        }
        dropout = float(best["dropout"])

        for seed in SEEDS_CONFIRM:
            print(f"\n===== Confirm {family.upper()} Transformer {task_name}, seed={seed} =====")
            set_seed(seed)
            model = build_model(family, task_name, dropout=dropout)
            cfg = make_cfg(**spec)
            row = run_trial(model, y_train, y_val, cfg, family=family, task=task_name, seed=seed)
            row["selected_from_run"] = best["run_name"]
            row["dropout"] = dropout
            row["params"] = count_trainable_params(model)

            if family == "standard":
                row.update(STANDARD_ARCH)
            else:
                row.update(SET_ARCH)

            confirm_rows.append(row)

transformer_confirm_runs_df = pd.DataFrame(confirm_rows)
transformer_confirm_runs_df

===== Confirm SET Transformer coordinate, seed=42 =====
epoch=001 train_loss=0.6240 val_loss=0.2178 score=-50.9434
epoch=005 train_loss=0.0665 val_loss=0.0654 score=-29.6377
epoch=010 train_loss=0.0194 val_loss=0.0187 score=-14.3379
epoch=015 train_loss=0.0149 val_loss=0.0170 score=-13.9878
epoch=020 train_loss=0.0132 val_loss=0.0151 score=-12.1393
epoch=025 train_loss=0.0117 val_loss=0.0150 score=-12.1671
epoch=030 train_loss=0.0110 val_loss=0.0155 score=-12.3121
epoch=035 train_loss=0.0107 val_loss=0.0149 score=-12.2240
epoch=040 train_loss=0.0104 val_loss=0.0143 score=-11.4285
epoch=045 train_loss=0.0100 val_loss=0.0142 score=-11.5515

===== Confirm SET Transformer coordinate, seed=123 =====
epoch=001 train_loss=1.0159 val_loss=1.2596 score=-142.6338
epoch=005 train_loss=0.0579 val_loss=0.0517 score=-24.5665
epoch=010 train_loss=0.0291 val_loss=0.0310 score=-18.1998
epoch=015 train_loss=0.0209 val_loss=0.0252 score=-16.8225
epoch=020 train_loss=0.0148 val_loss=0.0167 score=-13.4469
epoch=025 train_loss=0.0134 val_loss=0.0185 score=-14.6860
epoch=030 train_loss=0.0123 val_loss=0.0151 score=-12.1155
epoch=035 train_loss=0.0116 val_loss=0.0166 score=-12.9589
epoch=040 train_loss=0.0103 val_loss=0.0172 score=-12.2725

===== Confirm SET Transformer coordinate, seed=999 =====
epoch=001 train_loss=0.6302 val_loss=0.1985 score=-50.2432
epoch=005 train_loss=0.0620 val_loss=0.0584 score=-26.9736
epoch=010 train_loss=0.0217 val_loss=0.0246 score=-16.9056
epoch=015 train_loss=0.0157 val_loss=0.0190 score=-15.8751
epoch=020 train_loss=0.0141 val_loss=0.0159 score=-13.3804
epoch=025 train_loss=0.0121 val_loss=0.0145 score=-12.7137
epoch=030 train_loss=0.0116 val_loss=0.0144 score=-12.5342
epoch=035 train_loss=0.0111 val_loss=0.0138 score=-11.7017
epoch=040 train_loss=0.0108 val_loss=0.0143 score=-12.2403
epoch=045 train_loss=0.0106 val_loss=0.0138 score=-11.9622

===== Confirm SET Transformer joint, seed=42 =====
epoch=001 train_loss=2.5041 val_loss=2.6689 score=0.0954
epoch=005 train_loss=1.1624 val_loss=1.0694 score=0.5527
epoch=010 train_loss=0.6818 val_loss=0.6754 score=0.7741
epoch=015 train_loss=0.2333 val_loss=0.3598 score=0.8992
epoch=020 train_loss=0.1454 val_loss=0.3538 score=0.9199
epoch=025 train_loss=0.0700 val_loss=0.3771 score=0.9199
epoch=030 train_loss=0.0634 val_loss=0.4103 score=0.9181
epoch=035 train_loss=0.0513 val_loss=0.4073 score=0.9235
epoch=040 train_loss=0.0385 val_loss=0.3617 score=0.9307
epoch=045 train_loss=0.0296 val_loss=0.3880 score=0.9253
epoch=050 train_loss=0.0232 val_loss=0.3732 score=0.9316
epoch=055 train_loss=0.0194 val_loss=0.3773 score=0.9388

===== Confirm SET Transformer joint, seed=123 =====
epoch=001 train_loss=2.5263 val_loss=2.5493 score=0.0414
epoch=005 train_loss=0.9793 val_loss=0.9499 score=0.5563
epoch=010 train_loss=0.4538 val_loss=0.5660 score=0.8146
epoch=015 train_loss=0.1628 val_loss=0.2894 score=0.9289
epoch=020 train_loss=0.0975 val_loss=0.4839 score=0.8758
epoch=025 train_loss=0.0548 val_loss=0.3295 score=0.9334
epoch=030 train_loss=0.0363 val_loss=0.3306 score=0.9325
epoch=035 train_loss=0.0322 val_loss=0.3334 score=0.9388

===== Confirm SET Transformer joint, seed=999 =====
epoch=001 train_loss=2.4715 val_loss=2.6306 score=0.0711
epoch=005 train_loss=0.9635 val_loss=0.9076 score=0.6427
epoch=010 train_loss=0.5581 val_loss=0.5501 score=0.7939
epoch=015 train_loss=0.3771 val_loss=0.5407 score=0.8344
epoch=020 train_loss=0.2200 val_loss=0.3571 score=0.9109
epoch=025 train_loss=0.1296 val_loss=0.3559 score=0.9181
epoch=030 train_loss=0.0809 val_loss=0.3683 score=0.9280
epoch=035 train_loss=0.0444 val_loss=0.4898 score=0.9055
epoch=040 train_loss=0.0383 val_loss=0.3649 score=0.9352
epoch=045 train_loss=0.0241 val_loss=0.3498 score=0.9451
epoch=050 train_loss=0.0258 val_loss=0.4471 score=0.9208
epoch=055 train_loss=0.0210 val_loss=0.3508 score=0.9442
epoch=060 train_loss=0.0190 val_loss=0.3564 score=0.9415
epoch=065 train_loss=0.0159 val_loss=0.3706 score=0.9433
epoch=070 train_loss=0.0173 val_loss=0.3780 score=0.9442

===== Confirm SET Transformer multitask, seed=42 =====
epoch=001 train_loss=2.5584 val_loss=3.0424 score=0.0783
epoch=005 train_loss=1.1720 val_loss=1.1219 score=0.4932
epoch=010 train_loss=0.7349 val_loss=0.6124 score=0.7867
epoch=015 train_loss=0.2509 val_loss=0.3821 score=0.8731
epoch=020 train_loss=0.1201 val_loss=0.2250 score=0.9370
epoch=025 train_loss=0.0921 val_loss=0.2957 score=0.9262
epoch=030 train_loss=0.0421 val_loss=0.3068 score=0.9325
epoch=035 train_loss=0.0333 val_loss=0.2471 score=0.9523
epoch=040 train_loss=0.0270 val_loss=0.2969 score=0.9451
epoch=045 train_loss=0.0228 val_loss=0.2698 score=0.9478
epoch=050 train_loss=0.0213 val_loss=0.2655 score=0.9523

===== Confirm SET Transformer multitask, seed=123 =====
epoch=001 train_loss=2.5424 val_loss=2.3778 score=0.0999
epoch=005 train_loss=1.0761 val_loss=0.9246 score=0.6688
epoch=010 train_loss=0.4072 val_loss=0.3108 score=0.9046
epoch=015 train_loss=0.1574 val_loss=0.2746 score=0.9289
epoch=020 train_loss=0.1019 val_loss=0.5226 score=0.8704
epoch=025 train_loss=0.0666 val_loss=0.2622 score=0.9442
epoch=030 train_loss=0.0579 val_loss=0.2786 score=0.9451
epoch=035 train_loss=0.0445 val_loss=0.3171 score=0.9424
epoch=040 train_loss=0.0252 val_loss=0.3111 score=0.9406
epoch=045 train_loss=0.0166 val_loss=0.3436 score=0.9415
epoch=050 train_loss=0.0151 val_loss=0.3359 score=0.9442
epoch=055 train_loss=0.0122 val_loss=0.3438 score=0.9442

===== Confirm SET Transformer multitask, seed=999 =====
epoch=001 train_loss=2.5643 val_loss=2.5604 score=0.1278
epoch=005 train_loss=1.2001 val_loss=0.9492 score=0.5698
epoch=010 train_loss=0.6315 val_loss=0.6027 score=0.7831
epoch=015 train_loss=0.1567 val_loss=0.2305 score=0.9406
epoch=020 train_loss=0.0955 val_loss=0.2926 score=0.9289
epoch=025 train_loss=0.0503 val_loss=0.3045 score=0.9361
epoch=030 train_loss=0.0358 val_loss=0.3225 score=0.9289
epoch=035 train_loss=0.0306 val_loss=0.3350 score=0.9397
epoch=040 train_loss=0.0293 val_loss=0.3208 score=0.9424
epoch=045 train_loss=0.0278 val_loss=0.3312 score=0.9406
epoch=050 train_loss=0.0238 val_loss=0.3508 score=0.9352
epoch=055 train_loss=0.0246 val_loss=0.3316 score=0.9397

===== Confirm STANDARD Transformer coordinate, seed=42 =====
epoch=001 train_loss=0.8530 val_loss=0.2810 score=-60.0412
epoch=005 train_loss=0.0498 val_loss=0.0333 score=-19.6223
epoch=010 train_loss=0.0182 val_loss=0.0219 score=-16.6348
epoch=015 train_loss=0.0155 val_loss=0.0153 score=-12.1013
epoch=020 train_loss=0.0137 val_loss=0.0142 score=-10.7464
epoch=025 train_loss=0.0130 val_loss=0.0131 score=-10.4370
epoch=030 train_loss=0.0121 val_loss=0.0139 score=-10.9107
epoch=035 train_loss=0.0112 val_loss=0.0129 score=-10.1854
epoch=040 train_loss=0.0112 val_loss=0.0130 score=-10.2326
epoch=045 train_loss=0.0106 val_loss=0.0129 score=-10.2531
epoch=050 train_loss=0.0104 val_loss=0.0129 score=-10.2818

===== Confirm STANDARD Transformer coordinate, seed=123 =====
epoch=001 train_loss=0.6550 val_loss=0.3019 score=-65.5710
epoch=005 train_loss=0.0589 val_loss=0.0493 score=-25.6346
epoch=010 train_loss=0.0193 val_loss=0.0172 score=-13.3681
epoch=015 train_loss=0.0166 val_loss=0.0178 score=-13.4683
epoch=020 train_loss=0.0137 val_loss=0.0147 score=-11.1726
epoch=025 train_loss=0.0134 val_loss=0.0193 score=-14.7991
epoch=030 train_loss=0.0127 val_loss=0.0159 score=-11.6595
epoch=035 train_loss=0.0117 val_loss=0.0147 score=-10.8436
epoch=040 train_loss=0.0106 val_loss=0.0136 score=-10.6373
epoch=045 train_loss=0.0103 val_loss=0.0143 score=-10.4938
epoch=050 train_loss=0.0103 val_loss=0.0135 score=-11.3365

===== Confirm STANDARD Transformer coordinate, seed=999 =====
epoch=001 train_loss=0.7009 val_loss=0.2594 score=-57.2864
epoch=005 train_loss=0.0566 val_loss=0.0387 score=-22.0287
epoch=010 train_loss=0.0200 val_loss=0.0202 score=-14.8125
epoch=015 train_loss=0.0156 val_loss=0.0154 score=-11.6996
epoch=020 train_loss=0.0139 val_loss=0.0154 score=-12.1599
epoch=025 train_loss=0.0125 val_loss=0.0149 score=-11.1932
epoch=030 train_loss=0.0117 val_loss=0.0139 score=-10.7692
epoch=035 train_loss=0.0115 val_loss=0.0150 score=-11.2292
epoch=040 train_loss=0.0113 val_loss=0.0141 score=-10.8183

===== Confirm STANDARD Transformer joint, seed=42 =====
epoch=001 train_loss=2.4170 val_loss=2.0730 score=0.2349
epoch=005 train_loss=0.7688 val_loss=0.8291 score=0.6796
epoch=010 train_loss=0.3904 val_loss=0.5758 score=0.8353
epoch=015 train_loss=0.1991 val_loss=0.3527 score=0.9037
epoch=020 train_loss=0.0886 val_loss=0.3024 score=0.9280
epoch=025 train_loss=0.0743 val_loss=0.5888 score=0.8839
epoch=030 train_loss=0.0310 val_loss=0.5480 score=0.9091
epoch=035 train_loss=0.0253 val_loss=0.3220 score=0.9478
epoch=040 train_loss=0.0218 val_loss=0.4092 score=0.9352
epoch=045 train_loss=0.0159 val_loss=0.4340 score=0.9289

===== Confirm STANDARD Transformer joint, seed=123 =====
epoch=001 train_loss=2.4115 val_loss=2.0687 score=0.1566
epoch=005 train_loss=0.8301 val_loss=0.8146 score=0.7039
epoch=010 train_loss=0.4539 val_loss=0.5870 score=0.8416
epoch=015 train_loss=0.3090 val_loss=0.5712 score=0.8695
epoch=020 train_loss=0.1596 val_loss=0.3712 score=0.9127
epoch=025 train_loss=0.0977 val_loss=0.3231 score=0.9253
epoch=030 train_loss=0.0507 val_loss=0.3137 score=0.9415
epoch=035 train_loss=0.0373 val_loss=0.2877 score=0.9541
epoch=040 train_loss=0.0350 val_loss=0.3543 score=0.9406
epoch=045 train_loss=0.0177 val_loss=0.3074 score=0.9604
epoch=050 train_loss=0.0177 val_loss=0.3201 score=0.9523

===== Confirm STANDARD Transformer joint, seed=999 =====
epoch=001 train_loss=2.3171 val_loss=1.9936 score=0.2259
epoch=005 train_loss=0.7932 val_loss=0.8625 score=0.7012
epoch=010 train_loss=0.3513 val_loss=0.4710 score=0.8767
epoch=015 train_loss=0.1049 val_loss=0.3303 score=0.9370
epoch=020 train_loss=0.0790 val_loss=0.3020 score=0.9406
epoch=025 train_loss=0.0587 val_loss=0.2843 score=0.9478
epoch=030 train_loss=0.0415 val_loss=0.2356 score=0.9577
epoch=035 train_loss=0.0312 val_loss=0.3354 score=0.9343
epoch=040 train_loss=0.0217 val_loss=0.3102 score=0.9433

===== Confirm STANDARD Transformer multitask, seed=42 =====
epoch=001 train_loss=2.4844 val_loss=2.0762 score=0.1224
epoch=005 train_loss=0.7756 val_loss=0.5978 score=0.7777
epoch=010 train_loss=0.3972 val_loss=0.8663 score=0.7057
epoch=015 train_loss=0.2790 val_loss=0.3365 score=0.9145
epoch=020 train_loss=0.1605 val_loss=0.3195 score=0.9217
epoch=025 train_loss=0.0651 val_loss=0.2212 score=0.9469
epoch=030 train_loss=0.0528 val_loss=0.2553 score=0.9478
epoch=035 train_loss=0.0464 val_loss=0.2267 score=0.9514
epoch=040 train_loss=0.0271 val_loss=0.3122 score=0.9388
epoch=045 train_loss=0.0237 val_loss=0.2734 score=0.9532
epoch=050 train_loss=0.0217 val_loss=0.2838 score=0.9496

===== Confirm STANDARD Transformer multitask, seed=123 =====
epoch=001 train_loss=2.5832 val_loss=2.2355 score=0.1593
epoch=005 train_loss=0.5421 val_loss=0.5634 score=0.7957
epoch=010 train_loss=0.1948 val_loss=0.2724 score=0.9253
epoch=015 train_loss=0.0797 val_loss=0.5020 score=0.8857
epoch=020 train_loss=0.0555 val_loss=0.2424 score=0.9469
epoch=025 train_loss=0.0504 val_loss=0.3173 score=0.9406
epoch=030 train_loss=0.0382 val_loss=0.2764 score=0.9532
epoch=035 train_loss=0.0213 val_loss=0.2772 score=0.9532
epoch=040 train_loss=0.0162 val_loss=0.3262 score=0.9496

===== Confirm STANDARD Transformer multitask, seed=999 =====
epoch=001 train_loss=2.3439 val_loss=2.1901 score=0.1935
epoch=005 train_loss=0.7445 val_loss=0.8486 score=0.5608
epoch=010 train_loss=0.3971 val_loss=0.5263 score=0.8299
epoch=015 train_loss=0.2088 val_loss=0.3741 score=0.8974
epoch=020 train_loss=0.1415 val_loss=0.2434 score=0.9460
epoch=025 train_loss=0.0920 val_loss=0.3321 score=0.9343
epoch=030 train_loss=0.0423 val_loss=0.2813 score=0.9442

,family,task,run_name,seed,lr,weight_decay,batch_size,val_batch_size,max_epochs,patience,print_every,grad_clip_norm,best_epoch,epoch,train_loss,val_loss,score,coordinate_mean_euclidean,coordinate_rmse,coordinate_mean_euclidean_m,coordinate_rmse_m,selected_from_run,dropout,params,d_model,num_heads,num_sab_layers,dim_feedforward,num_seed_vectors,joint_accuracy,building_accuracy,floor_accuracy,nhead,num_layers
0,set,coordinate,confirm_set_coord_reg_1e3_wd5e4,42,0.0010,0.0005,256,512,50,10,5,1.0,37,37.0,0.010662,0.013415,-10.919728,0.123422,0.162111,10.919728,14.040860,set_coord_reg_1e3_wd5e4,0.1,481794,128,4.0,2.0,256,1.0,NaN,NaN,NaN,NaN,NaN
1,set,coordinate,confirm_set_coord_reg_1e3_wd5e4,123,0.0010,0.0005,256,512,50,10,5,1.0,31,31.0,0.012176,0.015095,-11.927882,0.132098,0.171883,11.927882,15.296345,set_coord_reg_1e3_wd5e4,0.1,481794,128,4.0,2.0,256,1.0,NaN,NaN,NaN,NaN,NaN
2,set,coordinate,confirm_set_coord_reg_1e3_wd5e4,999,0.0010,0.0005,256,512,50,10,5,1.0,35,35.0,0.011053,0.013754,-11.701690,0.126201,0.165179,11.701690,15.537414,set_coord_reg_1e3_wd5e4,0.1,481794,128,4.0,2.0,256,1.0,NaN,NaN,NaN,NaN,NaN
3,set,joint,confirm_set_joint_lowreg_5e4_wd5e4,42,0.0005,0.0005,256,512,80,15,5,1.0,43,43.0,0.034788,0.337773,0.944194,NaN,NaN,NaN,NaN,set_joint_lowreg_5e4_wd5e4,0.1,483213,128,4.0,2.0,256,1.0,0.944194,0.9991,0.944194,NaN,NaN
4,set,joint,confirm_set_joint_lowreg_5e4_wd5e4,123,0.0005,0.0005,256,512,80,15,5,1.0,24,24.0,0.063250,0.299119,0.938794,NaN,NaN,NaN,NaN,set_joint_lowreg_5e4_wd5e4,0.1,483213,128,4.0,2.0,256,1.0,0.938794,0.9991,0.938794,NaN,NaN
5,set,joint,confirm_set_joint_lowreg_5e4_wd5e4,999,0.0005,0.0005,256,512,80,15,5,1.0,56,56.0,0.017075,0.364211,0.945995,NaN,NaN,NaN,NaN,set_joint_lowreg_5e4_wd5e4,0.1,483213,128,4.0,2.0,256,1.0,0.945995,0.9964,0.945995,NaN,NaN
6,set,multitask,confirm_set_mt_lowreg_5e4_wd5e4,42,0.0005,0.0005,256,512,80,15,5,1.0,38,38.0,0.030049,0.228611,0.955896,NaN,NaN,NaN,NaN,set_mt_lowreg_5e4_wd5e4,0.1,499080,128,4.0,2.0,256,1.0,0.955896,0.9982,0.956796,NaN,NaN
7,set,multitask,confirm_set_mt_lowreg_5e4_wd5e4,123,0.0005,0.0005,256,512,80,15,5,1.0,41,41.0,0.017943,0.289587,0.951395,NaN,NaN,NaN,NaN,set_mt_lowreg_5e4_wd5e4,0.1,499080,128,4.0,2.0,256,1.0,0.951395,1.0000,0.951395,NaN,NaN
8,set,multitask,confirm_set_mt_lowreg_5e4_wd5e4,999,0.0005,0.0005,256,512,80,15,5,1.0,40,40.0,0.029297,0.320847,0.942394,NaN,NaN,NaN,NaN,set_mt_lowreg_5e4_wd5e4,0.1,499080,128,4.0,2.0,256,1.0,0.942394,0.9964,0.944194,NaN,NaN
9,standard,coordinate,confirm_standard_coord_stable_1e3_wd1e4,42,0.0010,0.0001,256,512,50,10,5,1.0,48,48.0,0.010421,0.012643,-10.035570,0.115134,0.154969,10.035570,13.249066,standard_coord_stable_1e3_wd1e4,0.1,349442,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0
10,standard,coordinate,confirm_standard_coord_stable_1e3_wd1e4,123,0.0010,0.0001,256,512,50,10,5,1.0,47,47.0,0.010460,0.013004,-10.094238,0.116597,0.157019,10.094238,13.263235,standard_coord_stable_1e3_wd1e4,0.1,349442,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0
11,standard,coordinate,confirm_standard_coord_stable_1e3_wd1e4,999,0.0010,0.0001,256,512,50,10,5,1.0,30,30.0,0.011671,0.013872,-10.769171,0.124007,0.164324,10.769171,14.021434,standard_coord_stable_1e3_wd1e4,0.1,349442,128,NaN,NaN,256,NaN,NaN,NaN,NaN,4.0,2.0
12,standard,joint,confirm_standard_joint_reg_1e3_wd5e4,42,0.0010,0.0005,256,512,50,10,5,1.0,35,35.0,0.025253,0.322046,0.947795,NaN,NaN,NaN,NaN,standard_joint_reg_1e3_wd5e4,0.1,350861,128,NaN,NaN,256,NaN,0.947795,0.9982,0.947795,4.0,2.0
13,standard,joint,confirm_standard_joint_reg_1e3_wd5e4,123,0.0010,0.0005,256,512,50,10,5,1.0,47,47.0,0.016498,0.316108,0.962196,NaN,NaN,NaN,NaN,standard_joint_reg_1e3_wd5e4,0.1,350861,128,NaN,NaN,256,NaN,0.962196,0.9991,0.963096,4.0,2.0
14,standard,joint,confirm_standard_joint_reg_1e3_wd5e4,999,0.0010,0.0005,256,512,50,10,5,1.0,30,30.0,0.041471,0.235579,0.957696,NaN,NaN,NaN,NaN,standard_joint_reg_1e3_wd5e4,0.1,350861,128,NaN,NaN,256,NaN,0.957696,0.9964,0.957696,4.0,2.0
15,standard,multitask,confirm_standard_mt_stable_1e3_wd1e4,42,0.0010,0.0001,256,512,50,10,5,1.0,41,41.0,0.026784,0.235624,0.960396,NaN,NaN,NaN,NaN,standard_mt_stable_1e3_wd1e4,0.1,366728,128,NaN,NaN,256,NaN,0.960396,1.0000,0.960396,4.0,2.0
16,standard,multitask,confirm_standard_mt_stable_1e3_wd1e4,123,0.0010,0.0001,256,512,50,10,5,1.0,33,33.0,0.026815,0.242280,0.960396,NaN,NaN,NaN,NaN,standard_mt_stable_1e3_wd1e4,0.1,366728,128,NaN,NaN,256,NaN,0.960396,0.9982,0.962196,4.0,2.0
17,standard,multitask,confirm_standard_mt_stable_1e3_wd1e4,999,0.0010,0.0001,256,512,50,10,5,1.0,22,22.0,0.092235,0.222644,0.954996,NaN,NaN,NaN,NaN,standard_mt_stable_1e3_wd1e4,0.1,366728,128,NaN,NaN,256,NaN,0.954996,0.9982,0.955896,4.0,2.0

## Confirmation summary

In [12]:
def summarize_confirm(df):
    if df.empty:
        return pd.DataFrame()
    agg = {
        "seed": "count",
        "score": ["mean", "std"],
        "best_epoch": "mean",
        "train_loss": "mean",
        "val_loss": "mean",
        "joint_accuracy": "mean",
        "building_accuracy": "mean",
        "floor_accuracy": "mean",
        "coordinate_mean_euclidean_m": "mean",
        "coordinate_rmse_m": "mean",
        "params": "first",
        "dropout": "first",
        "d_model": "first",
        "nhead": "first",
        "num_layers": "first",
        "num_heads": "first",
        "num_sab_layers": "first",
        "dim_feedforward": "first",
        "num_seed_vectors": "first",
    }
    available_agg = {k: v for k, v in agg.items() if k in df.columns}
    out = df.groupby(["family", "task", "run_name"]).agg(available_agg)
    out.columns = ["_".join(col).strip("_") if isinstance(col, tuple) else col for col in out.columns]
    out = out.reset_index().rename(columns={"seed_count": "runs"})
    return out

transformer_confirmation_summary = summarize_confirm(transformer_confirm_runs_df)
transformer_confirmation_summary

,family,task,run_name,runs,score_mean,score_std,best_epoch_mean,train_loss_mean,val_loss_mean,joint_accuracy_mean,building_accuracy_mean,floor_accuracy_mean,coordinate_mean_euclidean_m_mean,coordinate_rmse_m_mean,params_first,dropout_first,d_model_first,nhead_first,num_layers_first,num_heads_first,num_sab_layers_first,dim_feedforward_first,num_seed_vectors_first
0,set,coordinate,confirm_set_coord_reg_1e3_wd5e4,3,-11.516433,0.528993,34.333333,0.011297,0.014088,NaN,NaN,NaN,11.516433,14.958207,481794,0.1,128,NaN,NaN,4.0,2.0,256,1.0
1,set,joint,confirm_set_joint_lowreg_5e4_wd5e4,3,0.942994,0.003747,41.000000,0.038371,0.333701,0.942994,0.9982,0.942994,NaN,NaN,483213,0.1,128,NaN,NaN,4.0,2.0,256,1.0
2,set,multitask,confirm_set_mt_lowreg_5e4_wd5e4,3,0.949895,0.006875,39.666667,0.025763,0.279682,0.949895,0.9982,0.950795,NaN,NaN,499080,0.1,128,NaN,NaN,4.0,2.0,256,1.0
3,standard,coordinate,confirm_standard_coord_stable_1e3_wd1e4,3,-10.299660,0.407666,41.666667,0.010851,0.013173,NaN,NaN,NaN,10.299660,13.511245,349442,0.1,128,4.0,2.0,NaN,NaN,256,NaN
4,standard,joint,confirm_standard_joint_reg_1e3_wd5e4,3,0.955896,0.007368,37.333333,0.027741,0.291244,0.955896,0.9979,0.956196,NaN,NaN,350861,0.1,128,4.0,2.0,NaN,NaN,256,NaN
5,standard,multitask,confirm_standard_mt_stable_1e3_wd1e4,3,0.958596,0.003118,32.000000,0.048611,0.233516,0.958596,0.9988,0.959496,NaN,NaN,366728,0.1,128,4.0,2.0,NaN,NaN,256,NaN

## Final config dictionary to copy into baseline/robustness notebooks

In [13]:
FINAL_TUNED_CFGS = {
    family: {
        row["task"]: {
            "lr": float(row["lr"]),
            "weight_decay": float(row["weight_decay"]),
            "dropout": float(row["dropout"]),
            "grad_clip_norm": None if pd.isna(row.get("grad_clip_norm", None)) else float(row["grad_clip_norm"]),
            "max_epochs": int(row["max_epochs"]),
            "patience": int(row["patience"]),
            "print_every": 5,
            "batch_size": 256,
            "val_batch_size": 512,
            "architecture": (
                {k: int(row[k]) for k in ["d_model", "nhead", "num_layers", "dim_feedforward"] if k in row and pd.notna(row[k])}
                if family == "standard"
                else {k: int(row[k]) for k in ["d_model", "num_heads", "num_sab_layers", "dim_feedforward", "num_seed_vectors"] if k in row and pd.notna(row[k])}
            ),
        }
        for _, row in g.iterrows()
    }
    for family, g in best_by_family_task.groupby("family")
}

FINAL_TUNED_CFGS

{'set': {'coordinate': {'lr': 0.001,
   'weight_decay': 0.0005,
   'dropout': 0.1,
   'grad_clip_norm': 1.0,
   'max_epochs': 50,
   'patience': 10,
   'print_every': 5,
   'batch_size': 256,
   'val_batch_size': 512,
   'architecture': {'d_model': 128,
    'num_heads': 4,
    'num_sab_layers': 2,
    'dim_feedforward': 256,
    'num_seed_vectors': 1}},
  'joint': {'lr': 0.0005,
   'weight_decay': 0.0005,
   'dropout': 0.1,
   'grad_clip_norm': 1.0,
   'max_epochs': 80,
   'patience': 15,
   'print_every': 5,
   'batch_size': 256,
   'val_batch_size': 512,
   'architecture': {'d_model': 128,
    'num_heads': 4,
    'num_sab_layers': 2,
    'dim_feedforward': 256,
    'num_seed_vectors': 1}},
  'multitask': {'lr': 0.0005,
   'weight_decay': 0.0005,
   'dropout': 0.1,
   'grad_clip_norm': 1.0,
   'max_epochs': 80,
   'patience': 15,
   'print_every': 5,
   'batch_size': 256,
   'val_batch_size': 512,
   'architecture': {'d_model': 128,
    'num_heads': 4,
    'num_sab_layers': 2,
    'dim_feedforward': 256,
    'num_seed_vectors': 1}}},
 'standard': {'coordinate': {'lr': 0.001,
   'weight_decay': 0.0001,
   'dropout': 0.1,
   'grad_clip_norm': 1.0,
   'max_epochs': 50,
   'patience': 10,
   'print_every': 5,
   'batch_size': 256,
   'val_batch_size': 512,
   'architecture': {'d_model': 128,
    'nhead': 4,
    'num_layers': 2,
    'dim_feedforward': 256}},
  'joint': {'lr': 0.001,
   'weight_decay': 0.0005,
   'dropout': 0.1,
   'grad_clip_norm': 1.0,
   'max_epochs': 50,
   'patience': 10,
   'print_every': 5,
   'batch_size': 256,
   'val_batch_size': 512,
   'architecture': {'d_model': 128,
    'nhead': 4,
    'num_layers': 2,
    'dim_feedforward': 256}},
  'multitask': {'lr': 0.001,
   'weight_decay': 0.0001,
   'dropout': 0.1,
   'grad_clip_norm': 1.0,
   'max_epochs': 50,
   'patience': 10,
   'print_every': 5,
   'batch_size': 256,
   'val_batch_size': 512,
   'architecture': {'d_model': 128,
    'nhead': 4,
    'num_layers': 2,
    'dim_feedforward': 256}}}}

## Save outputs

In [14]:
OUTPUT_DIR = PROJECT_ROOT / "notebooks" / "logs" / "fair_tuning"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

if not transformer_tuning_df.empty:
    transformer_tuning_df.to_csv(OUTPUT_DIR / "transformer_tuning_grid_results.csv", index=False)
if not transformer_confirm_runs_df.empty:
    transformer_confirm_runs_df.to_csv(OUTPUT_DIR / "transformer_confirm_runs.csv", index=False)
if not transformer_confirmation_summary.empty:
    transformer_confirmation_summary.to_csv(OUTPUT_DIR / "transformer_confirmation_summary.csv", index=False)

print("Saved outputs to:", OUTPUT_DIR)

Saved outputs to: /storage/ice1/7/5/kw53/cs7643/tmp/CS7643-Project/notebooks/logs/fair_tuning